// <auto-generated />
using System;
using BugTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200607091913_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssueStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ProductOSVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IssueStatusId");

                    b.HasIndex("ProductOSVersionId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2020, 6, 6, 19, 48, 6, 396, DateTimeKind.Local).AddTicks(2010),
                            Description = @"Use the virtual SSL firewall, then you can program the virtual firewall! System.FormatException: Chief turquoise Isle
   at Bogus.DataSets.System.Exception() Cupiditate ipsum qui quasi quia odit accusantium. Ut minima quo occaecati at qui enim labore maxime vero. Quis id repudiandae. Qui enim sunt voluptate in velit repellat. Eius eveniet molestias.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 29,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2020, 6, 7, 9, 41, 1, 671, DateTimeKind.Local).AddTicks(5289),
                            Description = @"Use the redundant SAS interface, then you can override the redundant interface! System.BadImageFormatException: Rustic Concrete Tuna
File name: 'Assurance'
   at Bogus.DataSets.System.Exception() Ullam maiores est facilis consequatur. Vitae optio qui cumque aut dolor quos dolorum nisi. Quo quo ut illo tempore. Consectetur est ullam enim. Ut non sint dolore veniam.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 29,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2020, 6, 7, 4, 59, 19, 55, DateTimeKind.Local).AddTicks(8019),
                            Description = @"You can't program the alarm without compressing the haptic RSS alarm! System.BadImageFormatException: Liaison
File name: 'mobile'
   at Bogus.DataSets.System.Exception() Est maiores in aut quaerat laborum. Modi quaerat cupiditate consequatur. Reprehenderit a natus. Enim doloribus eius nam.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 48,
                            Resolution = "Sint aperiam placeat est qui possimus quo numquam quae. Esse dolor rerum rerum sed voluptatum unde est. Quibusdam aut nisi inventore. Fugit atque sed blanditiis est soluta. Accusantium qui eum autem aut corrupti voluptas.",
                            ResolutionDate = new DateTime(2022, 4, 27, 21, 56, 26, 291, DateTimeKind.Local).AddTicks(3815)
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2020, 6, 7, 10, 24, 10, 188, DateTimeKind.Local).AddTicks(9360),
                            Description = @"quantifying the monitor won't do anything, we need to index the 1080p SAS monitor! System.DivideByZeroException: Attempted to divide by zero.
   at Bogus.DataSets.System.Exception() Et nobis accusantium distinctio non quidem rerum. Dolorem eos neque non deleniti omnis et sapiente iste. Eum sed eum. Optio molestias quod molestias.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 16,
                            Resolution = "Harum molestiae numquam natus voluptas rerum. Modi similique aspernatur qui eius eum tempora porro. Dolor eius maiores rerum similique laudantium incidunt impedit.",
                            ResolutionDate = new DateTime(2022, 1, 28, 18, 46, 24, 198, DateTimeKind.Local).AddTicks(5050)
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2020, 6, 7, 6, 2, 59, 347, DateTimeKind.Local).AddTicks(8770),
                            Description = @"calculating the port won't do anything, we need to quantify the neural SMS port! System.ArgumentException: Finland 24/7 Pakistan Rupee (Parameter 'deliver')
   at Bogus.DataSets.System.Exception() Illo ut impedit neque nemo. Veniam placeat laudantium doloribus. Et nihil similique et voluptatem reiciendis ipsum. Velit tempora nesciunt totam veniam ipsa. Aperiam sapiente magni cupiditate voluptas delectus pariatur ipsum perferendis. Nulla soluta eum omnis qui quas eos ipsa nesciunt.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 50,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2020, 6, 7, 0, 35, 18, 782, DateTimeKind.Local).AddTicks(8114),
                            Description = @"We need to parse the back-end SAS bandwidth! System.OutOfMemoryException: PCI Fresh
   at Bogus.DataSets.System.Exception() Est occaecati et tempora eligendi ut. Voluptate suscipit rerum eum officiis. Ullam tempore omnis earum tenetur.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 44,
                            Resolution = "Distinctio adipisci neque eligendi aut saepe. Nihil quia dolores adipisci quia dolorum itaque nam omnis. Magnam iste eveniet. Ullam repellendus dolorem placeat est voluptatem. Quia ducimus earum aliquam consequatur facere.",
                            ResolutionDate = new DateTime(2022, 2, 27, 10, 1, 35, 628, DateTimeKind.Local).AddTicks(5089)
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2020, 6, 7, 6, 35, 22, 755, DateTimeKind.Local).AddTicks(625),
                            Description = @"generating the firewall won't do anything, we need to program the optical PNG firewall! System.IndexOutOfRangeException: Gorgeous Soft Fish Universal
   at Bogus.DataSets.System.Exception() Sunt aut veniam. Molestias consectetur ut non vero error ab ducimus. Eligendi sed expedita voluptas ut labore eveniet alias debitis. Mollitia necessitatibus dolores consectetur.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 4,
                            Resolution = "Amet iusto repudiandae illo quod eveniet totam dolorum voluptas qui. Sint non voluptas. Cum at et. Laudantium non soluta dolore facilis quia rerum suscipit. Quia sit consequuntur pariatur eos animi.",
                            ResolutionDate = new DateTime(2021, 4, 15, 5, 38, 25, 86, DateTimeKind.Local).AddTicks(8554)
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2020, 6, 7, 16, 0, 20, 937, DateTimeKind.Local).AddTicks(2298),
                            Description = @"If we back up the hard drive, we can get to the XML hard drive through the solid state XML hard drive! System.FormatException: Investor Turks and Caicos Islands parse
   at Bogus.DataSets.System.Exception() Quisquam ea sunt consequuntur esse quia tempore vel aut optio. Est illum quis repellat repudiandae deserunt porro. Perspiciatis omnis vel dolores nesciunt vitae. Voluptatibus quidem iure dicta aut ut. Perferendis esse eum voluptatem non quisquam repellendus fugiat sint. Eos ducimus rerum.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 17,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2020, 6, 7, 4, 51, 9, 196, DateTimeKind.Local).AddTicks(3383),
                            Description = @"Use the auxiliary FTP port, then you can copy the auxiliary port! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Quae voluptatibus laboriosam eaque asperiores et qui voluptas repudiandae et. Dolorem et vel repellat nam impedit aperiam vel ad quo. Ex odio aperiam temporibus.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 28,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2020, 6, 7, 0, 45, 5, 98, DateTimeKind.Local).AddTicks(455),
                            Description = @"We need to connect the haptic EXE bandwidth! System.FormatException: Exclusive
   at Bogus.DataSets.System.Exception() Excepturi minus alias deserunt modi beatae at mollitia nulla consequatur. Rerum non in. Expedita fugit enim aut perspiciatis autem.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 4,
                            Resolution = "Quas id sit dolorem id ducimus quibusdam cupiditate. Ad sed aut. Qui iusto earum rerum ab. Similique nostrum aspernatur hic numquam at et ut alias.",
                            ResolutionDate = new DateTime(2020, 11, 3, 14, 42, 49, 689, DateTimeKind.Local).AddTicks(5229)
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2020, 6, 7, 1, 16, 16, 52, DateTimeKind.Local).AddTicks(9680),
                            Description = @"Use the back-end COM circuit, then you can calculate the back-end circuit! System.IO.EndOfStreamException: Credit Card Account navigate Web
   at Bogus.DataSets.System.Exception() Ab ea ea ex excepturi est corrupti. Quae ut quia ut voluptatem cum quia adipisci. Magnam accusantium libero repudiandae quisquam quisquam modi beatae eius. Ad dolorum quae quo quos. Natus quos iure a iste labore sapiente et.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 46,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2020, 6, 6, 19, 57, 43, 341, DateTimeKind.Local).AddTicks(4542),
                            Description = @"You can't quantify the firewall without programming the bluetooth IB firewall! System.FormatException: Vista Money Market Account Belarussian Ruble
   at Bogus.DataSets.System.Exception() Ut numquam explicabo alias consectetur. Eius officia sit minus ut ut aut et. Laudantium rerum placeat consequatur dolore culpa voluptate. Aperiam quas perferendis eveniet quisquam molestiae neque nihil.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 5,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2020, 6, 6, 20, 32, 1, 291, DateTimeKind.Local).AddTicks(5901),
                            Description = @"Try to input the PCI sensor, maybe it will input the cross-platform sensor! System.OutOfMemoryException: Streamlined
   at Bogus.DataSets.System.Exception() Culpa est rerum fugit iure. Assumenda itaque veniam et nesciunt laborum veritatis magni. Modi qui sit sed occaecati autem ut pariatur qui qui. Perspiciatis magnam repudiandae id qui ut consequatur consequatur voluptatibus ea.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 14,
                            Resolution = "Ex beatae dolor nihil laborum ab placeat quibusdam aliquid. Est provident commodi ipsum est. Voluptas doloremque quo eos totam inventore et quia illum et. Sit accusantium velit maiores inventore quis placeat odit. Delectus odit quidem non distinctio rerum nobis.",
                            ResolutionDate = new DateTime(2020, 11, 23, 13, 0, 30, 126, DateTimeKind.Local).AddTicks(9141)
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2020, 6, 7, 15, 54, 51, 298, DateTimeKind.Local).AddTicks(612),
                            Description = @"I'll override the 1080p CSS feed, that should feed the CSS feed! System.IO.EndOfStreamException: wireless systematic Generic Fresh Sausages
   at Bogus.DataSets.System.Exception() Iusto ut voluptatum amet sint voluptatem perspiciatis aut et. Aliquam ratione id consequatur. Ipsa enim nisi et voluptatem ratione et in modi. Dignissimos rerum rerum assumenda.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 27,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2020, 6, 6, 22, 8, 10, 246, DateTimeKind.Local).AddTicks(5878),
                            Description = @"The JSON program is down, navigate the neural program so we can navigate the JSON program! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Doloribus qui tempore maiores deserunt voluptatibus esse. Officia laboriosam quod eos necessitatibus possimus inventore quisquam adipisci. Distinctio harum eum. Reprehenderit beatae ea perspiciatis nam laudantium doloribus fugiat aut. Ad voluptatem facere temporibus aut sit et suscipit sapiente. Explicabo error dolor reprehenderit omnis ratione qui minima quae.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 26,
                            Resolution = "Repellendus omnis libero maxime distinctio quisquam in. Deserunt dolores et velit sed ut reiciendis aut ea sint. Asperiores laborum consectetur similique aliquam. Architecto eum distinctio aperiam nihil quod autem deleniti consequatur modi. Autem non nobis et sint.",
                            ResolutionDate = new DateTime(2020, 12, 8, 7, 15, 45, 373, DateTimeKind.Local).AddTicks(2433)
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2020, 6, 7, 16, 17, 54, 944, DateTimeKind.Local).AddTicks(231),
                            Description = @"The GB alarm is down, back up the digital alarm so we can back up the GB alarm! System.IndexOutOfRangeException: input rich Rue
   at Bogus.DataSets.System.Exception() Repudiandae dolor quam quia tempore. Id eum ut. Dolor occaecati id impedit temporibus soluta molestias voluptatem molestiae mollitia.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 13,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2020, 6, 7, 9, 56, 25, 882, DateTimeKind.Local).AddTicks(2201),
                            Description = @"Try to program the AI application, maybe it will program the wireless application! System.IndexOutOfRangeException: Fantastic Rubber Chicken Handmade Cotton Ball
   at Bogus.DataSets.System.Exception() Est qui optio voluptas dolor ut excepturi qui ipsam modi. Hic quis culpa porro quis porro quod repellendus nam. Quasi dolorum autem. Sit voluptas doloribus et molestias nihil recusandae.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 11,
                            Resolution = "Perferendis consequatur laboriosam. Consectetur consequatur voluptatem ratione. Consequatur et et molestiae qui nam. Commodi optio distinctio ut quibusdam non. Ut est voluptatum.",
                            ResolutionDate = new DateTime(2021, 4, 21, 22, 0, 20, 463, DateTimeKind.Local).AddTicks(5469)
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2020, 6, 6, 22, 18, 31, 379, DateTimeKind.Local).AddTicks(4416),
                            Description = @"I'll back up the online SMS system, that should system the SMS system! System.BadImageFormatException: Internal
File name: 'streamline'
   at Bogus.DataSets.System.Exception() Eum quisquam veniam doloribus eos cumque ipsam neque. Accusamus sed voluptatem sed. Nesciunt quam ut quidem dolorem est non sint suscipit. Et sed sed. Ut autem dolor qui autem consequatur adipisci. Quaerat earum est exercitationem et fugiat iste animi libero.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 3,
                            Resolution = "Perspiciatis modi odio consectetur inventore cupiditate vitae eos. Accusantium sit doloribus. Ipsa harum dolores cum voluptas nihil sapiente ut voluptatem. Rem cupiditate tempora aut. Accusamus labore quia nihil eum harum quia sint nisi. Voluptatem perspiciatis ut recusandae excepturi asperiores.",
                            ResolutionDate = new DateTime(2021, 12, 3, 4, 48, 52, 55, DateTimeKind.Local).AddTicks(5557)
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2020, 6, 7, 10, 3, 18, 649, DateTimeKind.Local).AddTicks(2047),
                            Description = @"If we compress the circuit, we can get to the XML circuit through the optical XML circuit! System.ArgumentNullException: North Dakota (Parameter 'function')
   at Bogus.DataSets.System.Exception() Voluptatem commodi dicta libero omnis reprehenderit fuga suscipit neque. Maiores officiis nostrum. A id suscipit ratione quis minus cupiditate qui. Accusantium iste magni cum aut dignissimos voluptatibus vel doloribus quo. Similique consectetur excepturi alias molestias odio omnis cum.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 42,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2020, 6, 7, 0, 53, 3, 12, DateTimeKind.Local).AddTicks(6470),
                            Description = @"If we reboot the alarm, we can get to the XSS alarm through the redundant XSS alarm! System.ArithmeticException: compressing
   at Bogus.DataSets.System.Exception() Veritatis fugit facilis porro maxime necessitatibus. Est repellat nesciunt rerum. Voluptas modi suscipit quidem. Aut pariatur illo sunt quaerat provident sit ut cupiditate quibusdam. Ut cumque accusamus. Cumque possimus qui necessitatibus et quisquam.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 42,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2020, 6, 7, 15, 29, 56, 37, DateTimeKind.Local).AddTicks(5103),
                            Description = @"We need to quantify the optical PNG card! System.OutOfMemoryException: navigate AI
   at Bogus.DataSets.System.Exception() Aut qui laudantium deleniti modi. Qui soluta ullam. Et nihil aut est dignissimos. Numquam a veritatis saepe eveniet corrupti nam accusamus et. Autem et consectetur nisi asperiores asperiores necessitatibus voluptate est nemo. Labore autem est sit excepturi rem.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 40,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2020, 6, 6, 21, 55, 45, 7, DateTimeKind.Local).AddTicks(6150),
                            Description = @"Try to parse the AI firewall, maybe it will parse the neural firewall! System.IndexOutOfRangeException: Falkland Islands (Malvinas)
   at Bogus.DataSets.System.Exception() Aut occaecati accusantium et dolorem. Ut ipsa veritatis ullam eum temporibus provident molestiae. Dignissimos exercitationem facere numquam mollitia similique facilis quibusdam placeat natus. Distinctio ea sunt commodi et. Voluptatibus tempore iure quia dolore natus aperiam suscipit nobis. Eveniet doloremque natus voluptatem ratione qui voluptatibus eos qui voluptas.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 4,
                            Resolution = "Neque alias qui repudiandae nisi et ducimus ipsam. Deserunt natus veniam porro quo corrupti tenetur exercitationem dolore sed. Consequuntur eos quis aut dolorem autem debitis. Perferendis sunt et doloremque ea qui. Consectetur sed vitae et ut.",
                            ResolutionDate = new DateTime(2022, 5, 7, 2, 20, 52, 519, DateTimeKind.Local).AddTicks(6897)
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2020, 6, 7, 0, 21, 29, 90, DateTimeKind.Local).AddTicks(8195),
                            Description = @"Try to bypass the USB bus, maybe it will bypass the open-source bus! System.FormatException: Turkish Lira Sports, Beauty & Jewelery
   at Bogus.DataSets.System.Exception() Porro debitis repudiandae rerum placeat assumenda consectetur ut. Architecto quam impedit quidem. Maxime possimus aut veritatis atque ut quos neque.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 12,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2020, 6, 7, 8, 19, 8, 799, DateTimeKind.Local).AddTicks(3349),
                            Description = @"We need to back up the haptic SSL port! System.BadImageFormatException: Associate orange
File name: 'Awesome Frozen Car'
   at Bogus.DataSets.System.Exception() Perferendis ratione possimus inventore quasi enim ab aut. Ullam tempora et iste et quibusdam. Unde ut facilis quia. Accusantium modi ipsa facilis est iste ducimus minus corrupti. Necessitatibus sapiente dignissimos ut aut cumque qui.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 6,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2020, 6, 7, 15, 26, 42, 281, DateTimeKind.Local).AddTicks(7174),
                            Description = @"Try to connect the COM monitor, maybe it will connect the solid state monitor! System.FormatException: Supervisor content
   at Bogus.DataSets.System.Exception() Doloribus et porro velit vel quo id labore maiores. Suscipit veniam aut reprehenderit dolorem deleniti ea eum quis. Ut ducimus quia animi.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 14,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2020, 6, 6, 19, 25, 49, 776, DateTimeKind.Local).AddTicks(9216),
                            Description = @"You can't compress the program without transmitting the neural ADP program! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Impedit quaerat impedit qui accusamus numquam. Nulla rerum animi et praesentium eius itaque. Accusantium repudiandae doloribus tenetur et aliquam iusto at nobis.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 10,
                            Resolution = "Praesentium odit qui facere culpa dolore ab maiores minus. Natus iste architecto deserunt consequuntur odit totam vel ipsum. Corrupti fuga aperiam et ipsa voluptatem ut animi. Sint amet porro. Voluptatum non nam rerum non provident qui omnis. Tempore id consequatur est totam vero.",
                            ResolutionDate = new DateTime(2020, 10, 29, 7, 25, 55, 481, DateTimeKind.Local).AddTicks(5175)
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2020, 6, 7, 17, 12, 6, 558, DateTimeKind.Local).AddTicks(3654),
                            Description = @"Try to quantify the SCSI feed, maybe it will quantify the redundant feed! System.FormatException: grid-enabled extensible Branch
   at Bogus.DataSets.System.Exception() Et temporibus id minima corrupti ut quibusdam suscipit. Aut rerum consequuntur ad ea. Ab aliquam consequuntur. Hic laudantium qui autem. Porro sed sunt deserunt officia consequatur et quam nostrum. Maiores saepe nam laboriosam animi ea explicabo dicta.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 31,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2020, 6, 6, 20, 28, 29, 4, DateTimeKind.Local).AddTicks(4930),
                            Description = @"You can't synthesize the hard drive without copying the solid state COM hard drive! System.BadImageFormatException: Officer
File name: 'Money Market Account'
   at Bogus.DataSets.System.Exception() Voluptatum autem omnis incidunt consequatur necessitatibus laboriosam. Molestiae qui sed maiores ducimus veniam necessitatibus qui quibusdam ut. Aut doloribus at a. Autem est accusantium iusto.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 41,
                            Resolution = "Accusamus velit ad quis voluptas temporibus perferendis. Rem esse officiis natus consequatur. Quia placeat sint eum modi quo. Quam magni iure sint non qui at.",
                            ResolutionDate = new DateTime(2021, 3, 7, 18, 28, 2, 286, DateTimeKind.Local).AddTicks(5765)
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2020, 6, 7, 5, 6, 28, 658, DateTimeKind.Local).AddTicks(4714),
                            Description = @"We need to copy the optical JBOD alarm! System.IndexOutOfRangeException: Intelligent Fresh Hat application
   at Bogus.DataSets.System.Exception() Et dolores sit eum. Recusandae ducimus cupiditate vel doloremque omnis qui eos quos. Magni ea sint. Eum impedit impedit.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 11,
                            Resolution = "Ut et deserunt. Ullam vel delectus aperiam. Dolores sit aut deserunt quaerat saepe. Ut autem distinctio fugit in cupiditate. Fugiat iste iusto voluptatem eos ut architecto.",
                            ResolutionDate = new DateTime(2020, 11, 12, 11, 5, 4, 335, DateTimeKind.Local).AddTicks(1408)
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2020, 6, 7, 13, 50, 48, 636, DateTimeKind.Local).AddTicks(3709),
                            Description = @"I'll reboot the solid state XML driver, that should driver the XML driver! System.ArgumentException: Team-oriented (Parameter 'circuit')
   at Bogus.DataSets.System.Exception() Quia non ea ipsum animi sed. Quidem nam explicabo quo aut quibusdam est qui. Quisquam accusamus saepe sequi a et. Quibusdam consequatur consequuntur optio odio et id. Dolore impedit ut voluptas corporis.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 7,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2020, 6, 7, 3, 24, 31, 620, DateTimeKind.Local).AddTicks(8972),
                            Description = @"Use the open-source XML transmitter, then you can back up the open-source transmitter! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Natus quod dolorem eos asperiores. Nihil est repellat natus et voluptatum voluptas. Aut veritatis est totam in.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 28,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2020, 6, 7, 12, 36, 13, 917, DateTimeKind.Local).AddTicks(4264),
                            Description = @"We need to synthesize the digital CSS alarm! System.DivideByZeroException: Attempted to divide by zero.
   at Bogus.DataSets.System.Exception() Laudantium sit commodi aut rerum iusto excepturi aliquam ipsum. Et nemo repellendus. Consectetur maxime quia ut omnis aspernatur perspiciatis quas. Qui minima deserunt doloribus et nobis rerum impedit sit. Dolor laboriosam blanditiis deleniti voluptate.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 45,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2020, 6, 7, 14, 12, 57, 436, DateTimeKind.Local).AddTicks(5215),
                            Description = @"We need to navigate the back-end SSL matrix! System.OutOfMemoryException: Minnesota
   at Bogus.DataSets.System.Exception() Est labore sapiente ipsum voluptates animi nostrum ducimus vero. Veniam voluptate aut sit consequatur in minus. Quibusdam aut voluptatem rerum sit. Cumque et nemo ut unde.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 32,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2020, 6, 7, 8, 50, 23, 24, DateTimeKind.Local).AddTicks(3488),
                            Description = @"The SMS sensor is down, copy the solid state sensor so we can copy the SMS sensor! System.IndexOutOfRangeException: Dynamic
   at Bogus.DataSets.System.Exception() Sit sint laboriosam laudantium accusantium qui cumque doloribus minima. Provident nobis quia delectus eligendi ex debitis molestias aliquid fugiat. At nihil a quidem nobis vel quis sint est. Magni quia aspernatur omnis quam.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 7,
                            Resolution = "Soluta ut autem veniam similique. Eum dolor ex est rerum id itaque tenetur ex. Veniam nostrum est.",
                            ResolutionDate = new DateTime(2021, 3, 5, 6, 41, 12, 878, DateTimeKind.Local).AddTicks(6133)
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2020, 6, 7, 18, 55, 14, 571, DateTimeKind.Local).AddTicks(3334),
                            Description = @"If we synthesize the protocol, we can get to the SSL protocol through the multi-byte SSL protocol! System.BadImageFormatException: plum
File name: 'Shoes, Games & Movies'
   at Bogus.DataSets.System.Exception() Consectetur ut aliquid consequatur. Similique et et quam voluptatem voluptas porro eveniet repudiandae et. Aut consectetur amet libero. Non vel quia et rerum dolor aut.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 45,
                            Resolution = "Expedita sunt eligendi consectetur modi consequatur quas. Itaque dolor reprehenderit officiis est inventore sit. Eum eum laboriosam quidem esse voluptatum molestias est in. Tempora velit ad quod doloribus quos. Et magni omnis aut voluptas velit voluptatem. Optio in deserunt necessitatibus quaerat.",
                            ResolutionDate = new DateTime(2021, 8, 17, 19, 31, 3, 48, DateTimeKind.Local).AddTicks(8381)
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2020, 6, 7, 15, 0, 53, 341, DateTimeKind.Local).AddTicks(7832),
                            Description = @"The AGP card is down, parse the primary card so we can parse the AGP card! System.ArithmeticException: Auto Loan Account bypassing sexy
   at Bogus.DataSets.System.Exception() Ut est vitae provident eos ut nostrum sequi praesentium. Distinctio excepturi aut voluptas et incidunt voluptatem. Cumque qui ut debitis non consequuntur enim perferendis. Necessitatibus vel possimus magni est nesciunt qui esse numquam accusamus. Repellendus omnis ut non similique.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 34,
                            Resolution = "Eum ea doloribus et incidunt odit. Aut laborum rerum expedita et praesentium quis libero. Est et hic ut.",
                            ResolutionDate = new DateTime(2021, 9, 22, 18, 0, 11, 451, DateTimeKind.Local).AddTicks(478)
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2020, 6, 6, 22, 20, 4, 476, DateTimeKind.Local).AddTicks(6233),
                            Description = @"transmitting the program won't do anything, we need to index the multi-byte COM program! System.FormatException: portals static
   at Bogus.DataSets.System.Exception() Adipisci recusandae quae atque voluptatem et qui veniam laudantium eos. Itaque non error molestiae at sunt ducimus quo. Beatae id eum. Perferendis quis debitis blanditiis dolore sunt. Consequuntur eveniet quasi mollitia omnis perferendis aut omnis dolore sed.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 17,
                            Resolution = "Hic laborum temporibus deserunt vel. Et ex quisquam a quaerat. Recusandae in nisi cumque voluptatum necessitatibus ex velit repudiandae. Commodi rerum tenetur et quia ut enim. Aut qui accusantium et. Sed delectus sed a temporibus corrupti inventore dolores repudiandae aut.",
                            ResolutionDate = new DateTime(2022, 4, 22, 3, 45, 9, 52, DateTimeKind.Local).AddTicks(8743)
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2020, 6, 7, 8, 28, 44, 969, DateTimeKind.Local).AddTicks(692),
                            Description = @"I'll quantify the optical PCI feed, that should feed the PCI feed! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Non enim minus et molestiae consequatur. Exercitationem voluptatem sed ad quaerat consequatur alias velit. Reiciendis quaerat facere non numquam ut cupiditate. Facilis voluptatibus enim impedit. Aut velit est exercitationem.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 6,
                            Resolution = "Quas tenetur facilis unde ad. Consequatur fuga vel officia omnis animi rem dolor maiores. Aperiam saepe sit est eaque.",
                            ResolutionDate = new DateTime(2022, 2, 24, 8, 55, 25, 213, DateTimeKind.Local).AddTicks(958)
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2020, 6, 7, 12, 20, 12, 378, DateTimeKind.Local).AddTicks(5526),
                            Description = @"The JSON array is down, quantify the primary array so we can quantify the JSON array! System.ArgumentException: quantify Coordinator (Parameter 'Mountains')
   at Bogus.DataSets.System.Exception() Ratione maiores veniam nam repellendus. Eius earum sed doloribus aspernatur ipsa. Unde sapiente repudiandae vel sed quibusdam inventore velit. Adipisci et ut aperiam. Quae sit eveniet ad expedita in.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 32,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2020, 6, 7, 11, 55, 25, 477, DateTimeKind.Local).AddTicks(725),
                            Description = @"compressing the feed won't do anything, we need to hack the haptic XSS feed! System.ArgumentException: Cambridgeshire override (Parameter 'Checking Account')
   at Bogus.DataSets.System.Exception() Quod et dolores hic autem. Molestiae placeat perferendis quia molestiae quidem porro dignissimos. Fuga aut et odit quam et unde ea. Dolor pariatur sed. Aliquam voluptatem voluptate delectus. Sapiente repudiandae placeat rerum et excepturi eos provident facere labore.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 29,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2020, 6, 7, 10, 8, 59, 735, DateTimeKind.Local).AddTicks(9207),
                            Description = @"If we program the system, we can get to the FTP system through the open-source FTP system! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Ut quaerat corrupti omnis labore est debitis. Blanditiis voluptatum eveniet nulla reiciendis est quo. Blanditiis dolor reiciendis est atque nostrum qui minus nisi itaque. Corrupti vel odio autem corrupti sunt. Ut id illum architecto rerum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 10,
                            Resolution = "Aliquid sequi et. Rerum in optio adipisci nostrum inventore est rerum unde sit. Placeat voluptas a minus facere non. Soluta nisi eos delectus necessitatibus eos nemo fugiat debitis quibusdam. Veritatis saepe aspernatur sit.",
                            ResolutionDate = new DateTime(2021, 4, 11, 17, 31, 8, 167, DateTimeKind.Local).AddTicks(1370)
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2020, 6, 7, 6, 26, 35, 926, DateTimeKind.Local).AddTicks(7847),
                            Description = @"You can't calculate the driver without generating the back-end THX driver! System.OutOfMemoryException: Developer IB Small
   at Bogus.DataSets.System.Exception() Esse ullam et iure quo sit soluta velit enim. Ratione incidunt quasi eum ut eum eum. Pariatur est laborum voluptas eveniet voluptas inventore maiores odio sunt. Qui ut atque maxime veritatis distinctio laboriosam. Tenetur qui quam rerum impedit nemo iusto quos velit possimus. Dolorem ab praesentium nesciunt quia dicta qui.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 18,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2020, 6, 7, 7, 50, 53, 211, DateTimeKind.Local).AddTicks(3394),
                            Description = @"You can't reboot the array without transmitting the primary THX array! System.IO.FileNotFoundException: File not found...
File name: 'jcyqmhjh.owf'
   at Bogus.DataSets.System.Exception() Impedit maxime necessitatibus ut quia doloremque doloremque omnis quaerat. Consectetur itaque sed totam. Facere libero et enim tempora iure eum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 21,
                            Resolution = "In deserunt et ut laboriosam nam corrupti aut. Velit molestiae molestiae consequuntur et eum et praesentium. Ad eos incidunt dolorem et natus. Aut ad expedita sint aut.",
                            ResolutionDate = new DateTime(2022, 4, 24, 13, 35, 6, 166, DateTimeKind.Local).AddTicks(6367)
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2020, 6, 7, 13, 7, 36, 787, DateTimeKind.Local).AddTicks(2308),
                            Description = @"Use the auxiliary SAS sensor, then you can parse the auxiliary sensor! System.IO.EndOfStreamException: Dale Cambridgeshire
   at Bogus.DataSets.System.Exception() Labore beatae et in cum illum. Eius sequi deserunt. Nobis distinctio quos. Odio aut est quia impedit dolorum tempora repellat amet. Labore dolores sunt omnis ipsam perferendis illum quo consequatur. Voluptatem necessitatibus molestiae.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 36,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2020, 6, 7, 13, 10, 47, 621, DateTimeKind.Local).AddTicks(1415),
                            Description = @"Try to navigate the THX transmitter, maybe it will navigate the redundant transmitter! System.BadImageFormatException: Sports compress
File name: 'auxiliary'
   at Bogus.DataSets.System.Exception() Dolorum odio quia et praesentium. In enim ut at praesentium quisquam omnis qui ut. Blanditiis suscipit culpa omnis est.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 45,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2020, 6, 7, 12, 16, 12, 638, DateTimeKind.Local).AddTicks(8080),
                            Description = @"The THX array is down, synthesize the haptic array so we can synthesize the THX array! System.IO.FileNotFoundException: File not found...
File name: '4wdgqdmx.fpw'
   at Bogus.DataSets.System.Exception() Et et iusto et. Facilis quaerat nihil et sint est est blanditiis dolorem quam. Ullam ullam incidunt culpa culpa soluta excepturi. Sed hic quia odio perspiciatis rem fugit.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 46,
                            Resolution = "Quae dolor inventore rem doloribus voluptatem et in consequatur. Sunt dolorem qui consequatur et incidunt qui atque quod omnis. Illum animi deleniti temporibus deleniti molestiae.",
                            ResolutionDate = new DateTime(2021, 6, 28, 7, 35, 52, 233, DateTimeKind.Local).AddTicks(8772)
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2020, 6, 7, 18, 52, 13, 316, DateTimeKind.Local).AddTicks(1213),
                            Description = @"Try to override the HDD sensor, maybe it will override the virtual sensor! System.ArithmeticException: Tasty Metal Pizza Practical Wooden Shoes Fantastic Rubber Bacon
   at Bogus.DataSets.System.Exception() Aliquid voluptas fugit accusantium rem illum neque nesciunt in. Modi odio voluptas quibusdam dolore dolor dolorem inventore ut. Occaecati unde recusandae optio dolor impedit quia et esse. Blanditiis est iure quas ut laudantium consequatur qui. Non laborum alias error et et qui fuga.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 24,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2020, 6, 6, 22, 14, 29, 307, DateTimeKind.Local).AddTicks(5572),
                            Description = @"Use the multi-byte XML card, then you can transmit the multi-byte card! System.NotImplementedException: The method or operation is not implemented.
   at Bogus.DataSets.System.Exception() Omnis dolores explicabo maxime. Ullam in ab suscipit non repellendus ipsum quis. Impedit adipisci sint voluptatibus doloremque. Illo dicta repellat.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 12,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2020, 6, 7, 16, 16, 17, 538, DateTimeKind.Local).AddTicks(9494),
                            Description = @"The SMTP system is down, back up the open-source system so we can back up the SMTP system! System.ArithmeticException: grey programming digital
   at Bogus.DataSets.System.Exception() Quidem soluta magnam sit quaerat sed. Ab nemo aliquam non amet. Quisquam eius quia quae. Sed tenetur cupiditate quo ducimus ullam vel aut. Officiis vel est ut voluptas. Impedit et unde sit qui neque eos.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 27,
                            Resolution = "Natus quia praesentium. Officia quia itaque aperiam sint quaerat officiis. Ipsa cum quis autem ducimus nihil non. Debitis harum dolor dolorem. Suscipit amet cum dolores voluptatem quia error ut excepturi corrupti. Quasi tempora qui neque.",
                            ResolutionDate = new DateTime(2021, 4, 11, 15, 44, 2, 116, DateTimeKind.Local).AddTicks(929)
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2020, 6, 7, 0, 6, 15, 717, DateTimeKind.Local).AddTicks(9766),
                            Description = @"We need to hack the digital XML sensor! System.IO.EndOfStreamException: Tasty Agent Future
   at Bogus.DataSets.System.Exception() Vel magnam vel libero. Porro sed et dignissimos nostrum tempore temporibus ut. Veritatis provident ipsam repudiandae minima autem dolorum. Et impedit tempore omnis. Ut qui consequatur excepturi ipsam vel. Dolor necessitatibus ipsa ut eos blanditiis nemo natus velit adipisci.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 11,
                            Resolution = ""
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssueStatusList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OSName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OSName = "Windows"
                        },
                        new
                        {
                            Id = 2,
                            OSName = "Linux"
                        },
                        new
                        {
                            Id = 3,
                            OSName = "MacOS"
                        },
                        new
                        {
                            Id = 4,
                            OSName = "Android"
                        },
                        new
                        {
                            Id = 5,
                            OSName = "iOS"
                        },
                        new
                        {
                            Id = 6,
                            OSName = "Windows Mobile"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Day Trader Wannabe"
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Investment Overlord"
                        },
                        new
                        {
                            Id = 3,
                            ProductName = "Workout Planner"
                        },
                        new
                        {
                            Id = 4,
                            ProductName = "Social Anxiety Planner"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatingSystemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProductId", "OperatingSystemId", "VersionId");

                    b.HasIndex("OperatingSystemId");

                    b.HasIndex("VersionId");

                    b.ToTable("ProductOSVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperatingSystemId = 2,
                            ProductId = 3,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 2,
                            OperatingSystemId = 1,
                            ProductId = 1,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 3,
                            OperatingSystemId = 5,
                            ProductId = 4,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 4,
                            OperatingSystemId = 5,
                            ProductId = 1,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 5,
                            OperatingSystemId = 1,
                            ProductId = 1,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 6,
                            OperatingSystemId = 3,
                            ProductId = 2,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 7,
                            OperatingSystemId = 6,
                            ProductId = 4,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 8,
                            OperatingSystemId = 4,
                            ProductId = 1,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 9,
                            OperatingSystemId = 1,
                            ProductId = 3,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 10,
                            OperatingSystemId = 3,
                            ProductId = 4,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 11,
                            OperatingSystemId = 4,
                            ProductId = 1,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 12,
                            OperatingSystemId = 3,
                            ProductId = 1,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 13,
                            OperatingSystemId = 3,
                            ProductId = 4,
                            VersionId = 7
                        },
                        new
                        {
                            Id = 14,
                            OperatingSystemId = 3,
                            ProductId = 2,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 15,
                            OperatingSystemId = 4,
                            ProductId = 3,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 16,
                            OperatingSystemId = 6,
                            ProductId = 3,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 17,
                            OperatingSystemId = 6,
                            ProductId = 1,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 18,
                            OperatingSystemId = 4,
                            ProductId = 4,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 19,
                            OperatingSystemId = 4,
                            ProductId = 4,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 20,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 21,
                            OperatingSystemId = 6,
                            ProductId = 2,
                            VersionId = 7
                        },
                        new
                        {
                            Id = 22,
                            OperatingSystemId = 4,
                            ProductId = 3,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 23,
                            OperatingSystemId = 4,
                            ProductId = 1,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 24,
                            OperatingSystemId = 4,
                            ProductId = 2,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 25,
                            OperatingSystemId = 2,
                            ProductId = 4,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 26,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 27,
                            OperatingSystemId = 6,
                            ProductId = 3,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 28,
                            OperatingSystemId = 2,
                            ProductId = 4,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 29,
                            OperatingSystemId = 6,
                            ProductId = 3,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 30,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 31,
                            OperatingSystemId = 1,
                            ProductId = 2,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 32,
                            OperatingSystemId = 1,
                            ProductId = 4,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 33,
                            OperatingSystemId = 4,
                            ProductId = 3,
                            VersionId = 7
                        },
                        new
                        {
                            Id = 34,
                            OperatingSystemId = 4,
                            ProductId = 2,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 35,
                            OperatingSystemId = 4,
                            ProductId = 4,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 36,
                            OperatingSystemId = 5,
                            ProductId = 3,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 37,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 38,
                            OperatingSystemId = 6,
                            ProductId = 4,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 39,
                            OperatingSystemId = 4,
                            ProductId = 2,
                            VersionId = 7
                        },
                        new
                        {
                            Id = 40,
                            OperatingSystemId = 1,
                            ProductId = 3,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 41,
                            OperatingSystemId = 6,
                            ProductId = 2,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 42,
                            OperatingSystemId = 4,
                            ProductId = 2,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 43,
                            OperatingSystemId = 6,
                            ProductId = 1,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 44,
                            OperatingSystemId = 6,
                            ProductId = 1,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 45,
                            OperatingSystemId = 4,
                            ProductId = 4,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 46,
                            OperatingSystemId = 1,
                            ProductId = 2,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 47,
                            OperatingSystemId = 6,
                            ProductId = 2,
                            VersionId = 1
                        },
                        new
                        {
                            Id = 48,
                            OperatingSystemId = 4,
                            ProductId = 2,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 49,
                            OperatingSystemId = 4,
                            ProductId = 3,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 50,
                            OperatingSystemId = 1,
                            ProductId = 3,
                            VersionId = 1
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VersionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VersionName = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            VersionName = "1.1"
                        },
                        new
                        {
                            Id = 3,
                            VersionName = "1.2"
                        },
                        new
                        {
                            Id = 4,
                            VersionName = "1.3"
                        },
                        new
                        {
                            Id = 5,
                            VersionName = "2.0"
                        },
                        new
                        {
                            Id = 6,
                            VersionName = "2.1"
                        },
                        new
                        {
                            Id = 7,
                            VersionName = "2.2"
                        },
                        new
                        {
                            Id = 8,
                            VersionName = "2.3"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.HasOne("BugTracker.Data.Models.IssueStatus", "IssueStatus")
                        .WithMany()
                        .HasForeignKey("IssueStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.ProductOSVersion", "ProductOSVersion")
                        .WithMany()
                        .HasForeignKey("ProductOSVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.HasOne("BugTracker.Data.Models.OperatingSystem", "OperatingSystem")
                        .WithMany()
                        .HasForeignKey("OperatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
