// <auto-generated />
using System;
using BugTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200604094756_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssueStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ProductOSVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IssueStatusId");

                    b.HasIndex("ProductOSVersionId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2020, 6, 4, 18, 27, 37, 940, DateTimeKind.Local).AddTicks(4944),
                            Description = "Saepe laboriosam ipsum eum sunt quis. Corporis repellendus rerum. Animi expedita odit vero inventore ea assumenda ea qui. Quam molestiae in consectetur dolorum blanditiis facere. Numquam fugiat dicta voluptas corporis ratione.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 48,
                            Resolution = "Itaque praesentium laboriosam autem minus ipsa ut. Repellendus eaque sed aspernatur fugit omnis laboriosam aliquid veritatis cupiditate. Provident suscipit ipsam alias officia autem occaecati non.",
                            ResolutionDate = new DateTime(2022, 1, 21, 16, 43, 51, 558, DateTimeKind.Local).AddTicks(9750)
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2020, 6, 4, 2, 18, 13, 155, DateTimeKind.Local).AddTicks(2966),
                            Description = "Soluta nobis repudiandae praesentium sapiente iste voluptatem aspernatur illo. Et minima commodi tempore hic sit. Asperiores ab sit officiis ipsum est officiis. Nemo itaque id consectetur provident eos.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 47,
                            Resolution = "Nemo omnis quod maxime distinctio minus distinctio eveniet qui voluptatem. Dignissimos blanditiis quae itaque. Voluptates mollitia consectetur totam sint nostrum. Similique illo repellendus ad ex a asperiores magni et nemo.",
                            ResolutionDate = new DateTime(2021, 3, 17, 17, 56, 47, 605, DateTimeKind.Local).AddTicks(7746)
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2020, 6, 4, 16, 4, 28, 139, DateTimeKind.Local).AddTicks(1314),
                            Description = "Soluta minus quas ea. Temporibus excepturi nam nesciunt asperiores. Veniam quae quibusdam sunt enim nisi aliquam voluptates excepturi asperiores. Alias expedita et. Et cupiditate magnam error quas. Aut est et aut.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 39,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2020, 6, 4, 1, 51, 55, 777, DateTimeKind.Local).AddTicks(4764),
                            Description = "Accusantium porro laudantium ipsam et est reprehenderit odio. Quisquam sint dolore veniam incidunt rerum minus pariatur quod. Rerum doloribus esse deserunt quos dolor ea voluptatem ratione quis.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 35,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2020, 6, 4, 7, 35, 41, 132, DateTimeKind.Local).AddTicks(7010),
                            Description = "Non dolor nihil maxime. Amet ea velit similique et impedit tempora ut. Esse est reiciendis perspiciatis ipsum incidunt eligendi aut dolores dolorem. Eum omnis laborum autem totam. Qui ut aut earum eum consequatur voluptatem autem. Ut sed fuga nihil.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 33,
                            Resolution = "Ut quia ut laboriosam sapiente mollitia excepturi dicta quam. Maiores sapiente animi quos aut architecto facilis rerum omnis. Libero est consequuntur aut. Magnam quis dolore sequi consequatur quasi aut. Molestiae voluptatem voluptatem consectetur molestias dolor. Quis et asperiores placeat quas illum.",
                            ResolutionDate = new DateTime(2022, 1, 10, 3, 12, 37, 622, DateTimeKind.Local).AddTicks(459)
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2020, 6, 4, 17, 15, 26, 811, DateTimeKind.Local).AddTicks(8307),
                            Description = "Reiciendis cupiditate ad et animi dignissimos sit. Sed quis quibusdam. Placeat qui aspernatur vitae quaerat nobis. Doloribus qui voluptate quo. Non voluptas sunt quaerat molestiae aspernatur non quisquam. Aperiam in rerum dignissimos qui earum nam est temporibus.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 9,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2020, 6, 3, 19, 53, 26, 70, DateTimeKind.Local).AddTicks(2773),
                            Description = "Libero autem sed quia. Est et sit odio officiis quis. Autem minus praesentium animi sed asperiores maiores est qui aspernatur. Laboriosam consequatur sequi et corporis dolorem soluta. Sit porro enim architecto optio voluptas dolorum. Aspernatur fugiat non minus.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 45,
                            Resolution = "Ullam non fuga vel. Hic voluptatibus repellat sunt consequatur non. Enim officiis architecto laborum odio neque architecto harum. Nihil sequi quidem iusto maxime corrupti vel quibusdam. Dolorem facere fugit quia ad minus aut. Qui est consequatur aperiam eum.",
                            ResolutionDate = new DateTime(2020, 9, 10, 8, 43, 3, 695, DateTimeKind.Local).AddTicks(6688)
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2020, 6, 4, 0, 8, 1, 717, DateTimeKind.Local).AddTicks(6574),
                            Description = "Enim non fugiat fugiat voluptatem ratione ut similique consectetur velit. Ut nostrum et ea omnis. Ex ut et expedita omnis. Culpa consequatur necessitatibus earum expedita consequatur sed voluptatibus doloribus. Iusto asperiores et nulla. Accusamus sunt assumenda molestias molestias facilis aliquam hic aut.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 18,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2020, 6, 3, 20, 27, 46, 501, DateTimeKind.Local).AddTicks(8029),
                            Description = "Omnis voluptas laboriosam. Qui aliquam voluptatem voluptatem sed rerum sed. Numquam autem maiores at dolorum maxime sint cupiditate corrupti optio.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 29,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2020, 6, 4, 13, 39, 28, 246, DateTimeKind.Local).AddTicks(1095),
                            Description = "Eos vitae est vitae reprehenderit. Reiciendis iusto voluptate. Ducimus neque officia.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 8,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2020, 6, 4, 10, 55, 10, 681, DateTimeKind.Local).AddTicks(8760),
                            Description = "Nesciunt illum expedita in molestiae saepe beatae quos est adipisci. Eum adipisci nihil et qui aut quidem non quia suscipit. Nam corrupti voluptatem quae ut perspiciatis rem. Est ea quo voluptas perferendis omnis. Non qui et laboriosam ea magni atque quas. Itaque nihil perferendis est nobis dolorem ab.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 31,
                            Resolution = "Sint et debitis sapiente hic. Dolorem illo deserunt sint vero ut amet. Nisi recusandae neque dolor voluptatum. Consequatur et ut itaque culpa possimus ipsum culpa voluptas. Debitis voluptas esse pariatur quod cum dignissimos ut magni. Quaerat laboriosam quos laudantium.",
                            ResolutionDate = new DateTime(2021, 8, 3, 8, 6, 57, 859, DateTimeKind.Local).AddTicks(3270)
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2020, 6, 4, 5, 16, 27, 11, DateTimeKind.Local).AddTicks(3330),
                            Description = "Maiores maxime aut rerum. Eos minus hic nemo delectus quaerat velit. Molestias ut quasi rerum aut laboriosam recusandae. Et nulla qui.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 29,
                            Resolution = "Enim vel perspiciatis sed. Adipisci nihil culpa. Ex voluptate atque illo deserunt amet aspernatur repellendus.",
                            ResolutionDate = new DateTime(2022, 5, 17, 14, 46, 26, 321, DateTimeKind.Local).AddTicks(9676)
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2020, 6, 4, 6, 28, 4, 281, DateTimeKind.Local).AddTicks(9899),
                            Description = "Tenetur sapiente id sit aut dolor similique enim. Alias sequi laudantium rem ad nihil explicabo repellat officiis unde. Fugit non voluptatibus quidem corrupti quia et ut.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 27,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2020, 6, 4, 19, 45, 23, 696, DateTimeKind.Local).AddTicks(3701),
                            Description = "Neque molestiae cumque iusto assumenda labore eius commodi ipsam. Dolor qui perferendis sed. Omnis aperiam ipsa ut ullam dolore. Est accusantium est provident repellendus non distinctio illo quam. Suscipit et nihil quisquam odio illo non esse temporibus. Non sint et.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 18,
                            Resolution = "Enim aliquid consequatur expedita tempora quidem voluptas sit. Voluptatibus et amet rem qui facilis eos quos ullam. Consequatur qui cupiditate maxime reiciendis ut eligendi pariatur. Libero maxime natus.",
                            ResolutionDate = new DateTime(2020, 6, 5, 1, 54, 20, 183, DateTimeKind.Local).AddTicks(8346)
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2020, 6, 4, 12, 14, 10, 509, DateTimeKind.Local).AddTicks(3856),
                            Description = "Exercitationem sapiente dolor sit hic. Quam ea ipsam sed asperiores qui id consequatur. Eaque ea et tempora dignissimos in vel maiores. Rerum sint voluptates incidunt voluptas minima. Ullam iste libero. Delectus minus aut fuga.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 34,
                            Resolution = "Quo occaecati expedita unde sunt vel voluptatem tempore placeat ut. Consequatur cumque quaerat consequatur vel fugit. Fugit cumque quia reiciendis excepturi. Excepturi numquam in sunt tempora ipsum at totam sint facere. Ut ratione temporibus vitae quae.",
                            ResolutionDate = new DateTime(2021, 3, 24, 6, 49, 1, 237, DateTimeKind.Local).AddTicks(5656)
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2020, 6, 4, 1, 25, 31, 32, DateTimeKind.Local).AddTicks(7117),
                            Description = "Cupiditate ipsum id saepe quam. Est et quia quia qui repudiandae aut nostrum iure. Quibusdam consectetur beatae. Dolores optio doloremque. Temporibus possimus nemo.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 41,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2020, 6, 3, 23, 37, 51, 121, DateTimeKind.Local).AddTicks(4323),
                            Description = "Nulla quisquam delectus omnis ipsam perferendis consequatur in iste. Quia ut earum nemo asperiores odio dolores deserunt officia. Est et dolores eum eos ut odit. Dignissimos dolore veritatis suscipit nobis sint quasi aliquam. Laborum porro repellendus vel quas.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 9,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2020, 6, 4, 6, 6, 3, 688, DateTimeKind.Local).AddTicks(1800),
                            Description = "Deleniti voluptas et. Officia aliquam sit consequuntur nisi qui eos quidem est et. Magni nemo voluptas temporibus. Accusantium labore id fugit aut officiis et. Sit voluptatem eum quaerat. Esse fuga eveniet culpa ut.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 16,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2020, 6, 4, 3, 49, 20, 652, DateTimeKind.Local).AddTicks(8598),
                            Description = "Tempore amet reiciendis rerum debitis incidunt autem ipsum. Dolor dolore aspernatur et doloremque placeat aspernatur. Qui dolor earum voluptatem possimus aut nostrum ex. Magnam unde ipsa quis impedit. Ut excepturi et non et non et consequatur consequatur pariatur. Voluptatum aspernatur voluptatem eum et.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 5,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2020, 6, 4, 1, 29, 22, 574, DateTimeKind.Local).AddTicks(9502),
                            Description = "Quisquam aperiam ea minus blanditiis est ut aut reiciendis reiciendis. Aut porro itaque. Ut corrupti unde optio deserunt aut.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 9,
                            Resolution = "Pariatur voluptate repudiandae nemo nobis officia mollitia reiciendis dolorem magni. Architecto commodi et minus sapiente. Consectetur repellendus non est magni totam totam ea adipisci. Ut eum quisquam. Cupiditate beatae repellat eum aut voluptatem fuga modi laboriosam.",
                            ResolutionDate = new DateTime(2021, 1, 28, 11, 49, 51, 841, DateTimeKind.Local).AddTicks(7124)
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2020, 6, 3, 19, 57, 47, 987, DateTimeKind.Local).AddTicks(3634),
                            Description = "Et vel velit ut ducimus sed. Ratione placeat iusto alias laudantium qui magnam deleniti. Eveniet unde reiciendis rerum libero dolorem nihil quisquam. Temporibus et iusto aut laudantium nemo velit commodi.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 37,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2020, 6, 4, 17, 38, 36, 688, DateTimeKind.Local).AddTicks(9999),
                            Description = "Reiciendis eligendi qui. Dolorem amet quia quos aut consequuntur qui rerum. Iste reiciendis suscipit assumenda. Quia inventore nemo ut rerum nemo non ex numquam. Corrupti rem dolorem non a porro atque quam.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 1,
                            Resolution = "Provident eveniet consequatur. Amet perferendis ut accusantium delectus dignissimos aut. Ea sit perferendis deleniti consequatur laudantium. Voluptatum labore expedita. Enim voluptatem quis magni deserunt aspernatur est. Reprehenderit ut necessitatibus perferendis.",
                            ResolutionDate = new DateTime(2020, 8, 3, 21, 2, 45, 636, DateTimeKind.Local).AddTicks(8495)
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2020, 6, 3, 23, 48, 21, 166, DateTimeKind.Local).AddTicks(1732),
                            Description = "Voluptates ut nemo et aliquid voluptatem quia dolores. Velit laborum eos possimus commodi esse eum est unde ipsa. Quis repellat id pariatur rerum aut aspernatur illum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 27,
                            Resolution = "Est sit alias adipisci non ducimus cum velit similique sed. Possimus laudantium repellendus architecto. Excepturi omnis totam ut animi alias harum sapiente totam. Ducimus quasi natus soluta labore ipsa itaque quasi sed quisquam.",
                            ResolutionDate = new DateTime(2022, 3, 8, 16, 0, 1, 813, DateTimeKind.Local).AddTicks(4025)
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2020, 6, 4, 11, 17, 23, 52, DateTimeKind.Local).AddTicks(3764),
                            Description = "Inventore natus et exercitationem beatae veniam. Nostrum molestiae occaecati distinctio hic ut atque cum cupiditate nobis. Ipsum quo iure et voluptates recusandae blanditiis eaque totam. Ex odit cum inventore nobis quod optio aut voluptatibus sunt. Ut odit iusto vero deleniti rerum ut nisi. Nihil exercitationem nihil atque sit sunt.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 13,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2020, 6, 4, 4, 14, 50, 392, DateTimeKind.Local).AddTicks(1122),
                            Description = "Ipsa vel perferendis itaque quia voluptas id voluptatem et. Accusamus ut mollitia architecto et qui tenetur in et. Iste eligendi quasi et inventore in adipisci officiis mollitia minus. Nesciunt atque aliquam.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 32,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2020, 6, 4, 17, 33, 15, 517, DateTimeKind.Local).AddTicks(8657),
                            Description = "Quasi porro quo inventore laboriosam quam qui quidem. Ipsa autem est repudiandae voluptatem blanditiis. Corporis nostrum dolor deserunt ut tempore sit earum aut aut. Nihil culpa dolorum est doloribus. Aut voluptatum eveniet quo cumque assumenda doloribus.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 23,
                            Resolution = "Quidem nisi rerum perspiciatis laborum omnis possimus. Velit minima ea. Ab numquam molestias. Ut maxime excepturi debitis et.",
                            ResolutionDate = new DateTime(2021, 9, 20, 2, 9, 37, 439, DateTimeKind.Local).AddTicks(7943)
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2020, 6, 4, 5, 16, 42, 444, DateTimeKind.Local).AddTicks(4842),
                            Description = "Earum tempore natus. Id occaecati temporibus. Excepturi et aut occaecati fugit est aut esse sit. Reiciendis consequuntur rem. Beatae velit et et ea officiis dicta. Est in et dolorem nihil cupiditate qui qui.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 37,
                            Resolution = "Eos consequatur velit nostrum error in. Et eos et qui optio est vitae consequatur. Maxime illo fugiat.",
                            ResolutionDate = new DateTime(2021, 4, 15, 19, 3, 6, 387, DateTimeKind.Local).AddTicks(3900)
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2020, 6, 4, 17, 58, 8, 69, DateTimeKind.Local).AddTicks(7109),
                            Description = "Eos possimus et voluptatibus quia itaque quaerat voluptatem. Consequatur voluptate voluptatibus asperiores neque optio quasi doloremque aliquam nisi. In iusto rerum rem quo deserunt harum laudantium. Voluptas pariatur incidunt suscipit voluptatum ab et eius ipsam. Ut doloremque neque est voluptatem.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 6,
                            Resolution = "Voluptas est magnam delectus omnis perferendis voluptas eaque temporibus blanditiis. Error in deserunt ea quae maiores sed repudiandae. Nulla exercitationem et et nostrum sit culpa est. Architecto et ab aspernatur fuga facere excepturi.",
                            ResolutionDate = new DateTime(2022, 1, 21, 9, 25, 23, 130, DateTimeKind.Local).AddTicks(4719)
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2020, 6, 3, 22, 54, 17, 573, DateTimeKind.Local).AddTicks(5717),
                            Description = "Iste quisquam aliquam rem aut et. Sed sequi ut non nemo autem. Sunt occaecati dolor est. Aut est at porro earum autem est. Repellendus quia ipsam fuga quisquam maxime. Modi sed deserunt.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 5,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2020, 6, 4, 9, 57, 24, 554, DateTimeKind.Local).AddTicks(3768),
                            Description = "Et incidunt cupiditate suscipit sit consequatur. Iusto occaecati fugit minima nam eaque possimus voluptatibus aut eius. Aut aspernatur quas necessitatibus qui officiis. Nesciunt dolore nostrum expedita voluptates sit voluptatem. Repudiandae sequi velit enim molestias laudantium.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 19,
                            Resolution = "Veritatis quae dolor distinctio ut repudiandae iste quibusdam voluptatibus. Ex omnis et cumque consequatur enim. Voluptas et rerum. Voluptas facilis consequatur error minus accusantium aut molestiae quam. Odit corrupti ut autem tempore.",
                            ResolutionDate = new DateTime(2020, 9, 29, 16, 11, 43, 579, DateTimeKind.Local).AddTicks(2591)
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2020, 6, 4, 12, 39, 40, 503, DateTimeKind.Local).AddTicks(3347),
                            Description = "Facilis possimus dolore aliquid quas sapiente sunt enim amet. Voluptates est est est est voluptatem quia. Omnis laborum dolor magni veniam quia id sunt. Quo itaque provident quas quia iure est incidunt. Repudiandae eveniet repellendus optio suscipit veritatis delectus omnis consequatur.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 30,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2020, 6, 4, 4, 51, 28, 93, DateTimeKind.Local).AddTicks(1313),
                            Description = "At voluptatum voluptatum minus. Est corporis quia voluptas sed. Sit aspernatur aperiam dignissimos et ex aliquid rerum aut. Quia odit aut eum dignissimos provident sit qui. Nihil et quia architecto aperiam. Quibusdam maiores at officiis vel id delectus.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 39,
                            Resolution = "Voluptatem et occaecati saepe architecto sint. Consequuntur maxime recusandae modi eos sit. Fugit nihil modi et quam delectus aut modi. Beatae ad quisquam neque cupiditate fugit inventore consequatur fugit reiciendis. Non culpa nobis quos et porro.",
                            ResolutionDate = new DateTime(2021, 2, 4, 14, 44, 28, 665, DateTimeKind.Local).AddTicks(9989)
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2020, 6, 4, 15, 44, 34, 517, DateTimeKind.Local).AddTicks(2467),
                            Description = "Tenetur sequi adipisci tempore. Sit maiores omnis at aut laboriosam et omnis. Corporis incidunt sed dicta doloribus omnis provident.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 11,
                            Resolution = "Et debitis exercitationem commodi iure est laudantium. Quis mollitia ut et fugit veniam deserunt sunt. Eos consequatur voluptatem repellat voluptas illum consequatur.",
                            ResolutionDate = new DateTime(2021, 6, 2, 20, 59, 5, 637, DateTimeKind.Local).AddTicks(1466)
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2020, 6, 4, 9, 54, 55, 27, DateTimeKind.Local).AddTicks(3083),
                            Description = "Sunt unde in inventore. Et ipsam in excepturi in dolor et labore provident magni. Quod mollitia nesciunt eveniet blanditiis velit optio.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 20,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2020, 6, 4, 13, 0, 46, 448, DateTimeKind.Local).AddTicks(4748),
                            Description = "Nostrum eligendi consequuntur rerum perspiciatis nobis aut deleniti. Ut iste suscipit iusto ab. Rerum voluptate a non et temporibus error qui. Aliquid voluptate sed et et in voluptates.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 31,
                            Resolution = "Libero consequatur omnis dolor id. Et iusto vel autem ab voluptatum. Aut aspernatur est illo veniam pariatur blanditiis harum accusantium ea. Magnam ipsum impedit cum pariatur temporibus dignissimos facilis ea. Voluptates cumque illum.",
                            ResolutionDate = new DateTime(2021, 3, 19, 12, 23, 48, 232, DateTimeKind.Local).AddTicks(1410)
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2020, 6, 4, 17, 13, 4, 329, DateTimeKind.Local).AddTicks(2233),
                            Description = "Veritatis eveniet quis voluptas rerum quod id hic nihil sapiente. Natus sed nihil ea. Velit consequatur animi quibusdam. Illo autem beatae.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 49,
                            Resolution = "Ut blanditiis aliquam similique velit tempora commodi aut incidunt aut. Nemo quia enim nostrum. Et rerum hic qui odit sed deserunt eos similique.",
                            ResolutionDate = new DateTime(2020, 7, 11, 21, 44, 28, 320, DateTimeKind.Local).AddTicks(2056)
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2020, 6, 3, 23, 49, 25, 832, DateTimeKind.Local).AddTicks(866),
                            Description = "Sed repellat ratione vel ducimus illum sit quod aut. Culpa provident laboriosam voluptatem ut et. Non in quia aliquid itaque omnis. Dolorum aut consequatur aut nostrum ipsum.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2020, 6, 4, 10, 51, 39, 567, DateTimeKind.Local).AddTicks(354),
                            Description = "Sapiente dicta placeat facere rerum accusantium quas. Eum voluptatem voluptatem voluptas ut. Molestiae assumenda repudiandae et consectetur excepturi dolor labore optio adipisci.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 46,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2020, 6, 4, 14, 18, 56, 848, DateTimeKind.Local).AddTicks(905),
                            Description = "Quibusdam inventore est. Aliquid odit excepturi laboriosam tenetur eos. Eos sint ipsa nam.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 41,
                            Resolution = "Reiciendis libero nesciunt aliquam error itaque error rerum. Excepturi voluptatem nulla dolorum autem et ex eaque aut. Et in sed deleniti. In voluptate est iure.",
                            ResolutionDate = new DateTime(2021, 7, 14, 12, 57, 55, 44, DateTimeKind.Local).AddTicks(4448)
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2020, 6, 4, 13, 24, 0, 142, DateTimeKind.Local).AddTicks(7542),
                            Description = "Deleniti eligendi officiis omnis eveniet amet. Architecto rerum omnis sunt aperiam quae harum. Assumenda corporis ex illo consequatur neque architecto similique ipsam.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 44,
                            Resolution = "Impedit sit culpa nemo dignissimos consectetur reiciendis. Sequi numquam dolor dicta nam odio aliquid temporibus. Delectus beatae magnam. Voluptas aliquam consequatur ad qui natus qui. Pariatur eos quia porro quas consequatur dolor voluptatum corporis delectus. Magni fugiat amet quod.",
                            ResolutionDate = new DateTime(2021, 10, 15, 20, 9, 6, 369, DateTimeKind.Local).AddTicks(5674)
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2020, 6, 3, 21, 48, 34, 429, DateTimeKind.Local).AddTicks(2414),
                            Description = "Aut iure et. Enim voluptate quia natus nulla eveniet enim totam. Commodi dolore dolore aut sed omnis. Id consequatur reprehenderit quia labore minus.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 1,
                            Resolution = "Culpa sint quia incidunt molestiae beatae qui aperiam. Sapiente recusandae consequuntur molestiae quam. Et ut et.",
                            ResolutionDate = new DateTime(2021, 6, 26, 17, 49, 48, 703, DateTimeKind.Local).AddTicks(4379)
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2020, 6, 4, 9, 58, 10, 390, DateTimeKind.Local).AddTicks(1085),
                            Description = "Voluptas officiis asperiores molestias et in possimus sunt voluptatem ea. Rerum rerum facere libero sed omnis dolore et aut. Voluptatem unde voluptas. Culpa nobis mollitia omnis facere reiciendis. Ea sint ullam qui dolores. Consequuntur eaque repudiandae possimus.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 28,
                            Resolution = "Eum dolorem et. Consequuntur optio iste et tempore voluptas rem blanditiis. Distinctio distinctio quae. Est expedita laudantium.",
                            ResolutionDate = new DateTime(2022, 1, 10, 17, 20, 30, 819, DateTimeKind.Local).AddTicks(2883)
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2020, 6, 4, 13, 53, 0, 690, DateTimeKind.Local).AddTicks(287),
                            Description = "Nostrum iure et. Numquam ullam aspernatur. Et voluptas nam ab at necessitatibus nesciunt autem in. Ut atque est qui nulla maiores. Quia laudantium delectus ullam earum. Vitae nobis natus reprehenderit quia quia.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 3,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2020, 6, 3, 20, 18, 59, 891, DateTimeKind.Local).AddTicks(3425),
                            Description = "Tenetur libero placeat distinctio natus dolor. Eius ut sint modi pariatur ipsam non suscipit. Accusamus autem reprehenderit. Omnis distinctio blanditiis voluptates tempore.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 39,
                            Resolution = "Ut dolores totam. Enim ratione possimus sapiente. Et impedit nostrum exercitationem voluptas perspiciatis libero quod explicabo quo. Iste quia eum qui.",
                            ResolutionDate = new DateTime(2021, 2, 24, 11, 18, 33, 797, DateTimeKind.Local).AddTicks(1620)
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2020, 6, 4, 7, 36, 28, 477, DateTimeKind.Local).AddTicks(8632),
                            Description = "Rerum omnis voluptatibus est et nostrum quia ut. Fugit harum fuga velit. Occaecati et cupiditate molestiae.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 9,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2020, 6, 3, 20, 44, 30, 352, DateTimeKind.Local).AddTicks(6349),
                            Description = "Voluptatem rerum nostrum numquam quo doloribus quam consequatur sequi odit. Et ducimus accusamus nam voluptate quae nulla ut. Minima quidem non laudantium.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 6,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2020, 6, 4, 9, 31, 19, 464, DateTimeKind.Local).AddTicks(5304),
                            Description = "Nostrum aut impedit soluta. A nihil excepturi beatae suscipit reiciendis est odit voluptatum. Occaecati cupiditate architecto autem eos occaecati quia. Veritatis reiciendis eligendi iure perferendis. Repudiandae ducimus natus et voluptas et explicabo ut hic.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 20,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2020, 6, 3, 20, 44, 49, 875, DateTimeKind.Local).AddTicks(735),
                            Description = "Placeat suscipit quia. Non laboriosam enim non. Fuga quas in eum unde maiores qui velit rerum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 46,
                            Resolution = "Excepturi et et ipsum nesciunt velit rerum omnis voluptatem illo. Est sed possimus est cumque fugit sunt est nobis. Rerum esse molestiae nisi. Nihil unde in et laudantium eveniet fuga. Quod eos voluptatum occaecati. Id aut eos magni.",
                            ResolutionDate = new DateTime(2021, 6, 9, 4, 50, 29, 225, DateTimeKind.Local).AddTicks(7845)
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2020, 6, 4, 17, 19, 7, 825, DateTimeKind.Local).AddTicks(8535),
                            Description = "Deserunt cumque cupiditate nobis eveniet ipsum accusamus voluptatibus totam. Est sint eveniet officiis. Eveniet libero totam voluptatem vitae. Asperiores eligendi quis doloremque voluptas voluptate corporis. Magni odio aut laborum dolore ipsa sed ipsum asperiores porro. Quasi voluptatem qui tenetur et.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 43,
                            Resolution = "Molestias modi deserunt. Dicta aut voluptatem possimus voluptates. Nemo et sunt tempora voluptas et quia et velit in. Quidem ut eligendi. Et atque earum dolore sint amet recusandae fugiat. Illum accusantium itaque asperiores amet.",
                            ResolutionDate = new DateTime(2021, 3, 26, 19, 33, 34, 933, DateTimeKind.Local).AddTicks(7806)
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2020, 6, 3, 21, 7, 0, 521, DateTimeKind.Local).AddTicks(7055),
                            Description = "Voluptas porro dicta. Ea animi consequatur voluptatem et magni omnis similique. Suscipit autem soluta. Et eum quia qui tempore facere consequatur aut et ut. Consequuntur impedit nisi laudantium animi non et quisquam.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssueStatusList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OSName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OSName = "Windows"
                        },
                        new
                        {
                            Id = 2,
                            OSName = "Linux"
                        },
                        new
                        {
                            Id = 3,
                            OSName = "MacOS"
                        },
                        new
                        {
                            Id = 4,
                            OSName = "Android"
                        },
                        new
                        {
                            Id = 5,
                            OSName = "iOS"
                        },
                        new
                        {
                            Id = 6,
                            OSName = "Windows Mobile"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Awesome Concrete Chicken"
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Rustic Plastic Chips"
                        },
                        new
                        {
                            Id = 3,
                            ProductName = "Handmade Plastic Mouse"
                        },
                        new
                        {
                            Id = 4,
                            ProductName = "Unbranded Plastic Soap"
                        },
                        new
                        {
                            Id = 5,
                            ProductName = "Unbranded Plastic Fish"
                        },
                        new
                        {
                            Id = 6,
                            ProductName = "Incredible Rubber Table"
                        },
                        new
                        {
                            Id = 7,
                            ProductName = "Awesome Frozen Shoes"
                        },
                        new
                        {
                            Id = 8,
                            ProductName = "Licensed Cotton Keyboard"
                        },
                        new
                        {
                            Id = 9,
                            ProductName = "Intelligent Concrete Soap"
                        },
                        new
                        {
                            Id = 10,
                            ProductName = "Handmade Soft Salad"
                        },
                        new
                        {
                            Id = 11,
                            ProductName = "Refined Soft Pants"
                        },
                        new
                        {
                            Id = 12,
                            ProductName = "Licensed Granite Ball"
                        },
                        new
                        {
                            Id = 13,
                            ProductName = "Practical Cotton Chicken"
                        },
                        new
                        {
                            Id = 14,
                            ProductName = "Tasty Cotton Soap"
                        },
                        new
                        {
                            Id = 15,
                            ProductName = "Intelligent Fresh Pizza"
                        },
                        new
                        {
                            Id = 16,
                            ProductName = "Sleek Plastic Sausages"
                        },
                        new
                        {
                            Id = 17,
                            ProductName = "Licensed Cotton Table"
                        },
                        new
                        {
                            Id = 18,
                            ProductName = "Rustic Concrete Mouse"
                        },
                        new
                        {
                            Id = 19,
                            ProductName = "Gorgeous Soft Cheese"
                        },
                        new
                        {
                            Id = 20,
                            ProductName = "Awesome Frozen Car"
                        },
                        new
                        {
                            Id = 21,
                            ProductName = "Fantastic Steel Hat"
                        },
                        new
                        {
                            Id = 22,
                            ProductName = "Incredible Steel Hat"
                        },
                        new
                        {
                            Id = 23,
                            ProductName = "Intelligent Wooden Cheese"
                        },
                        new
                        {
                            Id = 24,
                            ProductName = "Practical Fresh Mouse"
                        },
                        new
                        {
                            Id = 25,
                            ProductName = "Handmade Rubber Shoes"
                        },
                        new
                        {
                            Id = 26,
                            ProductName = "Unbranded Granite Hat"
                        },
                        new
                        {
                            Id = 27,
                            ProductName = "Gorgeous Soft Pizza"
                        },
                        new
                        {
                            Id = 28,
                            ProductName = "Handcrafted Frozen Shirt"
                        },
                        new
                        {
                            Id = 29,
                            ProductName = "Practical Metal Hat"
                        },
                        new
                        {
                            Id = 30,
                            ProductName = "Intelligent Granite Fish"
                        },
                        new
                        {
                            Id = 31,
                            ProductName = "Sleek Frozen Shoes"
                        },
                        new
                        {
                            Id = 32,
                            ProductName = "Generic Rubber Table"
                        },
                        new
                        {
                            Id = 33,
                            ProductName = "Ergonomic Fresh Pizza"
                        },
                        new
                        {
                            Id = 34,
                            ProductName = "Incredible Concrete Bike"
                        },
                        new
                        {
                            Id = 35,
                            ProductName = "Rustic Plastic Hat"
                        },
                        new
                        {
                            Id = 36,
                            ProductName = "Gorgeous Cotton Tuna"
                        },
                        new
                        {
                            Id = 37,
                            ProductName = "Handmade Plastic Ball"
                        },
                        new
                        {
                            Id = 38,
                            ProductName = "Gorgeous Concrete Mouse"
                        },
                        new
                        {
                            Id = 39,
                            ProductName = "Rustic Soft Car"
                        },
                        new
                        {
                            Id = 40,
                            ProductName = "Ergonomic Fresh Gloves"
                        },
                        new
                        {
                            Id = 41,
                            ProductName = "Small Steel Soap"
                        },
                        new
                        {
                            Id = 42,
                            ProductName = "Ergonomic Frozen Sausages"
                        },
                        new
                        {
                            Id = 43,
                            ProductName = "Handcrafted Wooden Chair"
                        },
                        new
                        {
                            Id = 44,
                            ProductName = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 45,
                            ProductName = "Handcrafted Frozen Shoes"
                        },
                        new
                        {
                            Id = 46,
                            ProductName = "Generic Granite Tuna"
                        },
                        new
                        {
                            Id = 47,
                            ProductName = "Refined Concrete Gloves"
                        },
                        new
                        {
                            Id = 48,
                            ProductName = "Unbranded Granite Mouse"
                        },
                        new
                        {
                            Id = 49,
                            ProductName = "Sleek Plastic Tuna"
                        },
                        new
                        {
                            Id = 50,
                            ProductName = "Incredible Granite Bacon"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatingSystemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProductId", "OperatingSystemId", "VersionId");

                    b.HasIndex("OperatingSystemId");

                    b.HasIndex("VersionId");

                    b.ToTable("ProductOSVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperatingSystemId = 4,
                            ProductId = 15,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 2,
                            OperatingSystemId = 5,
                            ProductId = 40,
                            VersionId = 39
                        },
                        new
                        {
                            Id = 3,
                            OperatingSystemId = 5,
                            ProductId = 19,
                            VersionId = 29
                        },
                        new
                        {
                            Id = 4,
                            OperatingSystemId = 5,
                            ProductId = 24,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 5,
                            OperatingSystemId = 4,
                            ProductId = 44,
                            VersionId = 33
                        },
                        new
                        {
                            Id = 6,
                            OperatingSystemId = 4,
                            ProductId = 17,
                            VersionId = 43
                        },
                        new
                        {
                            Id = 7,
                            OperatingSystemId = 2,
                            ProductId = 1,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 8,
                            OperatingSystemId = 4,
                            ProductId = 35,
                            VersionId = 37
                        },
                        new
                        {
                            Id = 9,
                            OperatingSystemId = 2,
                            ProductId = 25,
                            VersionId = 33
                        },
                        new
                        {
                            Id = 10,
                            OperatingSystemId = 3,
                            ProductId = 40,
                            VersionId = 26
                        },
                        new
                        {
                            Id = 11,
                            OperatingSystemId = 6,
                            ProductId = 50,
                            VersionId = 3
                        },
                        new
                        {
                            Id = 12,
                            OperatingSystemId = 2,
                            ProductId = 36,
                            VersionId = 30
                        },
                        new
                        {
                            Id = 13,
                            OperatingSystemId = 2,
                            ProductId = 43,
                            VersionId = 24
                        },
                        new
                        {
                            Id = 14,
                            OperatingSystemId = 3,
                            ProductId = 39,
                            VersionId = 14
                        },
                        new
                        {
                            Id = 15,
                            OperatingSystemId = 6,
                            ProductId = 34,
                            VersionId = 20
                        },
                        new
                        {
                            Id = 16,
                            OperatingSystemId = 5,
                            ProductId = 39,
                            VersionId = 15
                        },
                        new
                        {
                            Id = 17,
                            OperatingSystemId = 2,
                            ProductId = 19,
                            VersionId = 50
                        },
                        new
                        {
                            Id = 18,
                            OperatingSystemId = 5,
                            ProductId = 40,
                            VersionId = 37
                        },
                        new
                        {
                            Id = 19,
                            OperatingSystemId = 4,
                            ProductId = 35,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 20,
                            OperatingSystemId = 2,
                            ProductId = 18,
                            VersionId = 31
                        },
                        new
                        {
                            Id = 21,
                            OperatingSystemId = 4,
                            ProductId = 6,
                            VersionId = 15
                        },
                        new
                        {
                            Id = 22,
                            OperatingSystemId = 3,
                            ProductId = 4,
                            VersionId = 49
                        },
                        new
                        {
                            Id = 23,
                            OperatingSystemId = 1,
                            ProductId = 4,
                            VersionId = 16
                        },
                        new
                        {
                            Id = 24,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 22
                        },
                        new
                        {
                            Id = 25,
                            OperatingSystemId = 2,
                            ProductId = 19,
                            VersionId = 43
                        },
                        new
                        {
                            Id = 26,
                            OperatingSystemId = 1,
                            ProductId = 42,
                            VersionId = 35
                        },
                        new
                        {
                            Id = 27,
                            OperatingSystemId = 5,
                            ProductId = 17,
                            VersionId = 22
                        },
                        new
                        {
                            Id = 28,
                            OperatingSystemId = 3,
                            ProductId = 19,
                            VersionId = 13
                        },
                        new
                        {
                            Id = 29,
                            OperatingSystemId = 2,
                            ProductId = 26,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 30,
                            OperatingSystemId = 1,
                            ProductId = 16,
                            VersionId = 33
                        },
                        new
                        {
                            Id = 31,
                            OperatingSystemId = 3,
                            ProductId = 27,
                            VersionId = 45
                        },
                        new
                        {
                            Id = 32,
                            OperatingSystemId = 5,
                            ProductId = 44,
                            VersionId = 39
                        },
                        new
                        {
                            Id = 33,
                            OperatingSystemId = 4,
                            ProductId = 50,
                            VersionId = 21
                        },
                        new
                        {
                            Id = 34,
                            OperatingSystemId = 5,
                            ProductId = 22,
                            VersionId = 31
                        },
                        new
                        {
                            Id = 35,
                            OperatingSystemId = 2,
                            ProductId = 50,
                            VersionId = 37
                        },
                        new
                        {
                            Id = 36,
                            OperatingSystemId = 3,
                            ProductId = 29,
                            VersionId = 27
                        },
                        new
                        {
                            Id = 37,
                            OperatingSystemId = 6,
                            ProductId = 44,
                            VersionId = 30
                        },
                        new
                        {
                            Id = 38,
                            OperatingSystemId = 1,
                            ProductId = 19,
                            VersionId = 29
                        },
                        new
                        {
                            Id = 39,
                            OperatingSystemId = 5,
                            ProductId = 9,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 40,
                            OperatingSystemId = 4,
                            ProductId = 3,
                            VersionId = 16
                        },
                        new
                        {
                            Id = 41,
                            OperatingSystemId = 5,
                            ProductId = 45,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 42,
                            OperatingSystemId = 4,
                            ProductId = 33,
                            VersionId = 50
                        },
                        new
                        {
                            Id = 43,
                            OperatingSystemId = 4,
                            ProductId = 27,
                            VersionId = 29
                        },
                        new
                        {
                            Id = 44,
                            OperatingSystemId = 6,
                            ProductId = 5,
                            VersionId = 20
                        },
                        new
                        {
                            Id = 45,
                            OperatingSystemId = 6,
                            ProductId = 14,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 46,
                            OperatingSystemId = 3,
                            ProductId = 42,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 47,
                            OperatingSystemId = 6,
                            ProductId = 26,
                            VersionId = 39
                        },
                        new
                        {
                            Id = 48,
                            OperatingSystemId = 3,
                            ProductId = 28,
                            VersionId = 8
                        },
                        new
                        {
                            Id = 49,
                            OperatingSystemId = 1,
                            ProductId = 3,
                            VersionId = 24
                        },
                        new
                        {
                            Id = 50,
                            OperatingSystemId = 5,
                            ProductId = 16,
                            VersionId = 47
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VersionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VersionName = "3.9.0.5"
                        },
                        new
                        {
                            Id = 2,
                            VersionName = "3.2.6.0"
                        },
                        new
                        {
                            Id = 3,
                            VersionName = "4.5.5.2"
                        },
                        new
                        {
                            Id = 4,
                            VersionName = "6.6.5.6"
                        },
                        new
                        {
                            Id = 5,
                            VersionName = "5.2.7.5"
                        },
                        new
                        {
                            Id = 6,
                            VersionName = "2.4.2.6"
                        },
                        new
                        {
                            Id = 7,
                            VersionName = "0.1.5.4"
                        },
                        new
                        {
                            Id = 8,
                            VersionName = "5.6.2.3"
                        },
                        new
                        {
                            Id = 9,
                            VersionName = "6.2.6.7"
                        },
                        new
                        {
                            Id = 10,
                            VersionName = "5.1.6.2"
                        },
                        new
                        {
                            Id = 11,
                            VersionName = "9.4.2.2"
                        },
                        new
                        {
                            Id = 12,
                            VersionName = "6.0.2.7"
                        },
                        new
                        {
                            Id = 13,
                            VersionName = "6.8.6.3"
                        },
                        new
                        {
                            Id = 14,
                            VersionName = "5.9.6.9"
                        },
                        new
                        {
                            Id = 15,
                            VersionName = "7.4.5.1"
                        },
                        new
                        {
                            Id = 16,
                            VersionName = "6.2.4.7"
                        },
                        new
                        {
                            Id = 17,
                            VersionName = "2.1.6.3"
                        },
                        new
                        {
                            Id = 18,
                            VersionName = "0.7.0.4"
                        },
                        new
                        {
                            Id = 19,
                            VersionName = "6.5.5.8"
                        },
                        new
                        {
                            Id = 20,
                            VersionName = "1.9.9.9"
                        },
                        new
                        {
                            Id = 21,
                            VersionName = "8.7.7.7"
                        },
                        new
                        {
                            Id = 22,
                            VersionName = "9.9.8.7"
                        },
                        new
                        {
                            Id = 23,
                            VersionName = "6.6.0.1"
                        },
                        new
                        {
                            Id = 24,
                            VersionName = "5.4.5.7"
                        },
                        new
                        {
                            Id = 25,
                            VersionName = "9.4.0.4"
                        },
                        new
                        {
                            Id = 26,
                            VersionName = "3.8.7.8"
                        },
                        new
                        {
                            Id = 27,
                            VersionName = "8.1.7.0"
                        },
                        new
                        {
                            Id = 28,
                            VersionName = "3.7.7.8"
                        },
                        new
                        {
                            Id = 29,
                            VersionName = "4.5.3.8"
                        },
                        new
                        {
                            Id = 30,
                            VersionName = "4.7.7.3"
                        },
                        new
                        {
                            Id = 31,
                            VersionName = "3.9.7.3"
                        },
                        new
                        {
                            Id = 32,
                            VersionName = "7.9.9.1"
                        },
                        new
                        {
                            Id = 33,
                            VersionName = "9.8.8.7"
                        },
                        new
                        {
                            Id = 34,
                            VersionName = "9.4.6.9"
                        },
                        new
                        {
                            Id = 35,
                            VersionName = "0.9.9.7"
                        },
                        new
                        {
                            Id = 36,
                            VersionName = "2.7.3.8"
                        },
                        new
                        {
                            Id = 37,
                            VersionName = "8.1.6.0"
                        },
                        new
                        {
                            Id = 38,
                            VersionName = "1.6.2.1"
                        },
                        new
                        {
                            Id = 39,
                            VersionName = "7.6.0.4"
                        },
                        new
                        {
                            Id = 40,
                            VersionName = "0.3.1.9"
                        },
                        new
                        {
                            Id = 41,
                            VersionName = "2.5.1.5"
                        },
                        new
                        {
                            Id = 42,
                            VersionName = "8.0.9.9"
                        },
                        new
                        {
                            Id = 43,
                            VersionName = "9.3.8.5"
                        },
                        new
                        {
                            Id = 44,
                            VersionName = "8.9.1.6"
                        },
                        new
                        {
                            Id = 45,
                            VersionName = "6.9.4.5"
                        },
                        new
                        {
                            Id = 46,
                            VersionName = "2.9.9.2"
                        },
                        new
                        {
                            Id = 47,
                            VersionName = "5.7.9.2"
                        },
                        new
                        {
                            Id = 48,
                            VersionName = "3.2.8.6"
                        },
                        new
                        {
                            Id = 49,
                            VersionName = "8.0.5.6"
                        },
                        new
                        {
                            Id = 50,
                            VersionName = "6.7.9.7"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.HasOne("BugTracker.Data.Models.IssueStatus", "IssueStatus")
                        .WithMany()
                        .HasForeignKey("IssueStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.ProductOSVersion", "ProductOSVersion")
                        .WithMany()
                        .HasForeignKey("ProductOSVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.HasOne("BugTracker.Data.Models.OperatingSystem", "OperatingSystem")
                        .WithMany()
                        .HasForeignKey("OperatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
