// <auto-generated />
using System;
using BugTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssueStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ProductOSVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IssueStatusId");

                    b.HasIndex("ProductOSVersionId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2020, 6, 2, 3, 35, 35, 911, DateTimeKind.Local).AddTicks(5443),
                            Description = "Quisquam accusamus explicabo tempora ipsa qui numquam. Deserunt eligendi ut exercitationem dolorem fugiat consequuntur. Magni laboriosam nostrum deserunt inventore aut veritatis qui voluptas temporibus. Culpa recusandae quod repellat similique qui. Consequatur voluptatem quia qui consequatur.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 24,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2020, 6, 2, 18, 33, 15, 739, DateTimeKind.Local).AddTicks(3604),
                            Description = "Deserunt similique et velit dolorum quibusdam qui excepturi. Quia fugit vel eligendi iusto est iusto. Consequatur non ea odit qui et neque sint. Odio nobis debitis animi esse officia rem delectus. Veniam eum laudantium.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 17,
                            Resolution = "Nostrum porro sed et. Laboriosam quia dolores consequatur sapiente praesentium sint consequatur cumque laudantium. Doloremque quidem animi pariatur eligendi. Quo voluptates laudantium aut facere unde ut qui. Voluptatem incidunt non aut quae.",
                            ResolutionDate = new DateTime(2021, 10, 3, 7, 23, 18, 135, DateTimeKind.Local).AddTicks(7703)
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2020, 6, 2, 19, 10, 18, 590, DateTimeKind.Local).AddTicks(1493),
                            Description = "Nihil vero quidem in. Quas quos voluptatum ipsa blanditiis sequi natus. Itaque cumque veniam. Ea voluptas harum et nihil non laboriosam est molestiae odio.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 6,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2020, 6, 1, 21, 29, 50, 599, DateTimeKind.Local).AddTicks(5518),
                            Description = "Sit ullam pariatur nesciunt veritatis rerum enim magni. Omnis placeat libero id in. Et quas qui. Repellendus suscipit qui sit.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 9,
                            Resolution = "Vel laboriosam sed corporis minima quia. Sit iure quia quis magni voluptatem voluptate repellat nisi. Sit dolorem facere et.",
                            ResolutionDate = new DateTime(2021, 9, 29, 0, 20, 7, 737, DateTimeKind.Local).AddTicks(9423)
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2020, 6, 2, 17, 7, 5, 354, DateTimeKind.Local).AddTicks(7196),
                            Description = "Maxime nisi ratione voluptatem repellat atque ut reiciendis enim optio. Et consequatur et. Iste distinctio sit est qui dolor consequatur magnam expedita. Iste iure recusandae minima sed qui.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2020, 6, 2, 11, 30, 16, 78, DateTimeKind.Local).AddTicks(5417),
                            Description = "Deleniti vero facere. Inventore distinctio ex corporis sequi quo odio consectetur tempore qui. Nemo illum debitis et deleniti.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 21,
                            Resolution = "Laborum animi libero. Molestiae voluptatem non consequatur totam. Aut sunt et laudantium expedita aspernatur corrupti placeat. Vel explicabo corrupti qui dignissimos aspernatur aperiam optio id.",
                            ResolutionDate = new DateTime(2022, 5, 10, 0, 24, 30, 86, DateTimeKind.Local).AddTicks(4214)
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2020, 6, 2, 19, 17, 45, 24, DateTimeKind.Local).AddTicks(8885),
                            Description = "Quae mollitia officiis accusantium sunt veritatis iusto ullam veniam. Aliquid non officiis laudantium. Dolorem vel consequatur aliquid nam. Recusandae quas est numquam sed vel. Cumque ea alias. Sed qui dolores inventore molestiae doloremque assumenda quod nostrum culpa.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 27,
                            Resolution = "Accusamus tempora sequi. Voluptas autem voluptas voluptatem est quos. Officiis occaecati mollitia iusto. Ducimus et ut expedita. Inventore eos et qui debitis. Laboriosam libero iusto tenetur at fugiat illum consectetur et.",
                            ResolutionDate = new DateTime(2020, 10, 28, 19, 39, 48, 232, DateTimeKind.Local).AddTicks(9202)
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2020, 6, 2, 11, 49, 23, 162, DateTimeKind.Local).AddTicks(2499),
                            Description = "Nihil tempore ab ut. In dolor mollitia est. Et ea ea sit maiores. Asperiores totam impedit accusantium itaque architecto. Odio eum sapiente quia eius. Veritatis saepe voluptatibus cumque.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 8,
                            Resolution = "Iure similique asperiores. Et pariatur dolore eum aut explicabo. Vel omnis soluta in.",
                            ResolutionDate = new DateTime(2021, 8, 13, 13, 24, 35, 317, DateTimeKind.Local).AddTicks(9925)
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2020, 6, 2, 6, 11, 57, 999, DateTimeKind.Local).AddTicks(8536),
                            Description = "Expedita voluptate dignissimos iusto molestiae in odit aut molestiae rem. Quam molestiae harum tempora ipsam qui sed quis delectus. Pariatur cumque ut. Quam eum sed ea.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 45,
                            Resolution = "Commodi mollitia animi totam et officiis. Facere minus necessitatibus dolorem aspernatur est non. Pariatur magnam aliquid eum est officia dolore consectetur natus eum.",
                            ResolutionDate = new DateTime(2021, 7, 8, 2, 29, 13, 194, DateTimeKind.Local).AddTicks(1654)
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2020, 6, 2, 2, 48, 18, 488, DateTimeKind.Local).AddTicks(1133),
                            Description = "Explicabo voluptas ducimus iure tempore fugit dolorem omnis. Dolor sint delectus nobis a sit. Dolorem voluptatem dolor excepturi quibusdam aut nihil ut ut. Maxime doloribus impedit.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 5,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2020, 6, 2, 16, 2, 25, 756, DateTimeKind.Local).AddTicks(1564),
                            Description = "Sed eveniet accusamus consequatur ducimus. Eos enim molestiae et voluptatem. Id officiis aspernatur non.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 20,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2020, 6, 2, 7, 4, 2, 920, DateTimeKind.Local).AddTicks(990),
                            Description = "Non est quaerat ut qui voluptatibus. Porro consequatur mollitia excepturi aliquid repudiandae voluptas. Illo reprehenderit et rerum necessitatibus occaecati fugiat placeat.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 42,
                            Resolution = "Nostrum fuga perspiciatis sed nam quis quo quasi eaque. Autem earum iure quam sed consequatur. Vel et quis atque. Dolor debitis veritatis enim accusamus necessitatibus. Sint error fuga dolores. Et ad quia necessitatibus repellendus necessitatibus.",
                            ResolutionDate = new DateTime(2021, 1, 10, 19, 57, 18, 291, DateTimeKind.Local).AddTicks(7246)
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2020, 6, 2, 15, 10, 42, 338, DateTimeKind.Local).AddTicks(6220),
                            Description = "Est ad porro amet. Nulla velit accusantium iusto rerum facilis impedit necessitatibus sed. Sit aliquid et qui est consequatur aliquid.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 47,
                            Resolution = "Ut doloremque aperiam et et maiores aliquam tempora. Molestiae esse voluptates expedita quibusdam iste doloremque fuga fugit. Et expedita fugiat reprehenderit iure. Aliquid accusamus eligendi eveniet qui. Ad eos nulla ducimus reiciendis error. Odit molestiae officia odio magnam totam.",
                            ResolutionDate = new DateTime(2020, 8, 2, 0, 41, 28, 559, DateTimeKind.Local).AddTicks(2415)
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2020, 6, 2, 15, 11, 35, 965, DateTimeKind.Local).AddTicks(1121),
                            Description = "Eius consequatur accusantium aut ut delectus earum ut. Quis optio magnam aut aut odio. Consequatur vero porro laboriosam iure est ut. Voluptatem vitae necessitatibus impedit. Doloribus laboriosam et. Odio temporibus animi illum odit cum tenetur.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 24,
                            Resolution = "Nulla numquam culpa et nemo quia. Ratione quam dolor. Laborum et est qui aut.",
                            ResolutionDate = new DateTime(2021, 2, 2, 9, 57, 25, 60, DateTimeKind.Local).AddTicks(9143)
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2020, 6, 2, 2, 47, 18, 795, DateTimeKind.Local).AddTicks(1855),
                            Description = "Non quaerat consequatur asperiores sequi aut sequi et. Aliquid dignissimos quo aut a qui beatae. Eius et doloremque qui. Sunt perferendis voluptas facere cumque dolor voluptas aut. Beatae velit quam eius dolorem. Porro saepe reiciendis.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 3,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2020, 6, 1, 20, 6, 12, 650, DateTimeKind.Local).AddTicks(1272),
                            Description = "Omnis recusandae ratione vero debitis. Quo quaerat quod enim. Est autem sequi in.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 32,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2020, 6, 1, 22, 55, 42, 587, DateTimeKind.Local).AddTicks(8532),
                            Description = "Commodi quidem laudantium. Asperiores repellat sint quia blanditiis nulla dolorem est. Libero beatae illum iste voluptatem rerum. Dolores qui blanditiis voluptatem maiores eos quis error quos. Quia est consequatur et voluptatibus quia rem ea.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 49,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2020, 6, 2, 4, 41, 48, 577, DateTimeKind.Local).AddTicks(4765),
                            Description = "Ut odio earum nesciunt est consequatur dolorem. Soluta sit aliquam reprehenderit ratione repellendus et quia. Animi velit a non. Non dolorum id ad et perspiciatis totam. Accusamus sunt dolore placeat debitis magnam aut amet et qui. Sunt ullam repellat nemo ipsam sit voluptatem minus commodi.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 44,
                            Resolution = "Saepe dignissimos molestias sed quia beatae culpa facere expedita. Possimus non perspiciatis sit enim facere vero impedit tenetur eum. Rerum ab ea quam est tenetur ut voluptatem blanditiis. Incidunt voluptatibus sit. Impedit deleniti recusandae dolorem corrupti voluptates sint.",
                            ResolutionDate = new DateTime(2021, 7, 7, 17, 13, 24, 146, DateTimeKind.Local).AddTicks(2140)
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2020, 6, 2, 11, 4, 20, 721, DateTimeKind.Local).AddTicks(5005),
                            Description = "Pariatur ratione dolorem recusandae dolore unde magnam. Numquam animi id consequuntur placeat eum alias ut. Enim vel dicta occaecati mollitia quam. Qui voluptatem nulla quam esse aut vel saepe in.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 16,
                            Resolution = "Asperiores repudiandae voluptatem. Autem vitae fuga consectetur omnis voluptatem neque. In et sit aut. Aut placeat fugit. Dolore non ipsam quis rerum assumenda consequatur aut et omnis. Qui libero aut laboriosam eligendi harum consequuntur consequatur.",
                            ResolutionDate = new DateTime(2020, 11, 9, 7, 35, 26, 426, DateTimeKind.Local).AddTicks(9788)
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2020, 6, 2, 15, 19, 13, 428, DateTimeKind.Local).AddTicks(2819),
                            Description = "Sed modi nihil fugiat non labore. Voluptas unde ipsa cumque. Ratione esse temporibus omnis ut et quaerat enim sunt. Necessitatibus necessitatibus qui illo. Voluptas corrupti quis est et.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 35,
                            Resolution = "Cupiditate quaerat at. Laboriosam ratione distinctio perspiciatis dolores tenetur est. Optio illo ea nostrum sit.",
                            ResolutionDate = new DateTime(2020, 12, 2, 10, 17, 15, 664, DateTimeKind.Local).AddTicks(9077)
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2020, 6, 1, 23, 58, 10, 294, DateTimeKind.Local).AddTicks(2692),
                            Description = "Sit in aspernatur non qui asperiores sunt. Vero numquam minima ut at. Fugit doloribus blanditiis. Perferendis sit vel aut nesciunt.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 36,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2020, 6, 2, 11, 0, 3, 711, DateTimeKind.Local).AddTicks(6425),
                            Description = "Totam minus id. Totam est tempore dolor vero voluptas est eum aut inventore. Provident dolor incidunt quia sapiente fugiat quo aperiam dolor.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 45,
                            Resolution = "Ut iure dignissimos est atque. Numquam quas neque nisi enim adipisci et quidem accusamus quo. Inventore quidem incidunt. Odio doloribus autem quibusdam ut maxime sint.",
                            ResolutionDate = new DateTime(2020, 11, 25, 20, 39, 22, 565, DateTimeKind.Local).AddTicks(8929)
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2020, 6, 2, 17, 50, 26, 202, DateTimeKind.Local).AddTicks(7806),
                            Description = "Facilis illum eius sint maxime quo beatae est et nisi. Aut quae voluptas aut corrupti sit ex totam consequatur. Nulla et et beatae. Et ut aperiam. Expedita perspiciatis est qui illo eos itaque omnis sapiente.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 20,
                            Resolution = "Magnam ullam voluptatem voluptatem nemo et laudantium. Est ea veritatis. Ad dolor iure delectus est. Voluptatem aut iusto error nobis sint quia quia facere optio. Nesciunt quasi impedit eos ut id ut ut aut et. Ea totam provident eum quaerat.",
                            ResolutionDate = new DateTime(2021, 9, 6, 17, 5, 5, 322, DateTimeKind.Local).AddTicks(8684)
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2020, 6, 1, 21, 22, 35, 307, DateTimeKind.Local).AddTicks(6165),
                            Description = "Sapiente optio quia. Ex ipsa et et neque unde omnis. Velit esse odio soluta eius aut et voluptas nobis. Blanditiis tempora impedit aut omnis. Reprehenderit dignissimos illum aliquam et laborum voluptas vel vero. Laborum asperiores aliquid.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 10,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2020, 6, 2, 16, 59, 56, 364, DateTimeKind.Local).AddTicks(8565),
                            Description = "Officia sunt inventore dolorem velit et distinctio velit recusandae et. Ipsum blanditiis aperiam accusantium nam. Quidem id doloribus. Nostrum sit dolores officiis dolores tempora quas et labore. Quis omnis vel ut hic illo blanditiis id.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 20,
                            Resolution = "Itaque cupiditate fugit minima aut. Ut neque voluptatem. Et voluptatibus rerum eum quos est sint quisquam.",
                            ResolutionDate = new DateTime(2021, 11, 17, 11, 1, 27, 249, DateTimeKind.Local).AddTicks(5275)
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2020, 6, 2, 1, 23, 15, 70, DateTimeKind.Local).AddTicks(3326),
                            Description = "Veritatis nihil debitis eaque. Fugiat in vel aperiam voluptatem ab natus. Quas perspiciatis enim ducimus. Est voluptatum voluptates adipisci ex distinctio iure qui maxime illo.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 31,
                            Resolution = "Necessitatibus vel et ut laudantium inventore ea dicta. Sint sed exercitationem iure et hic veritatis enim nesciunt dolor. Quaerat voluptatibus et architecto est beatae est expedita. Sequi eum consequatur.",
                            ResolutionDate = new DateTime(2022, 3, 26, 4, 58, 9, 540, DateTimeKind.Local).AddTicks(5713)
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2020, 6, 2, 16, 48, 9, 117, DateTimeKind.Local).AddTicks(1149),
                            Description = "Possimus dolorem autem nemo est. Accusantium accusamus aut deserunt similique doloribus velit. Ipsum aut nisi. Aut quia totam. Est dolorem inventore. Expedita aut ut accusantium sed corporis molestiae id.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 7,
                            Resolution = "Soluta rerum ea reprehenderit sed non eos nobis id qui. Quidem sint voluptatum sequi corrupti nulla recusandae eaque eius. Suscipit accusamus aliquid eius et sed sunt occaecati perspiciatis eveniet. Distinctio et qui et.",
                            ResolutionDate = new DateTime(2020, 10, 14, 22, 49, 36, 318, DateTimeKind.Local).AddTicks(4223)
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2020, 6, 2, 15, 10, 14, 3, DateTimeKind.Local).AddTicks(8818),
                            Description = "Aut consectetur repellendus qui dolores. Omnis cumque vitae quos facilis odit animi quia quod eos. Illo fuga dolore et necessitatibus ab ut hic.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 20,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2020, 6, 2, 17, 53, 6, 974, DateTimeKind.Local).AddTicks(5012),
                            Description = "Dolor quibusdam ipsam facere sed voluptatibus nobis tenetur minima. Molestias maiores sunt atque. Sint itaque magni amet maxime. Laboriosam omnis dolor laboriosam sint qui illum. Odio est corrupti odit.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 14,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2020, 6, 1, 23, 2, 10, 645, DateTimeKind.Local).AddTicks(3762),
                            Description = "Ut possimus dolor impedit omnis velit quod recusandae ipsam. Quo aperiam sed dolores debitis pariatur quia. Et sed esse quis voluptas et. Quo cupiditate voluptatem aut veniam est ea consequuntur sunt. Molestiae error voluptates error. Ipsa ea animi in.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 36,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2020, 6, 2, 11, 42, 47, 921, DateTimeKind.Local).AddTicks(2302),
                            Description = "Aliquam sed enim id aliquam et nobis. Enim tenetur itaque rerum porro illo doloremque autem nemo et. Reiciendis qui veniam. Debitis odit dolores aut nobis. Voluptas mollitia sint aut velit.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 9,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2020, 6, 2, 7, 23, 15, 818, DateTimeKind.Local).AddTicks(3739),
                            Description = "Fugit labore voluptatum at nihil. Sed suscipit perferendis molestiae nihil quos veniam. Non architecto numquam earum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 9,
                            Resolution = "Distinctio voluptatum molestias aliquam a fuga magnam quia aliquid. Repellendus autem aliquam exercitationem in nesciunt aut. Qui et possimus nihil repellat expedita unde ex nihil. Nemo molestiae et nostrum molestias aperiam consequatur quas earum doloremque. Magnam vero quia expedita fugit. Ut nisi modi qui aliquam et.",
                            ResolutionDate = new DateTime(2021, 1, 15, 11, 18, 34, 729, DateTimeKind.Local).AddTicks(9702)
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2020, 6, 2, 4, 0, 12, 334, DateTimeKind.Local).AddTicks(4434),
                            Description = "Cum magni deserunt consequatur qui delectus voluptatem. Nemo beatae exercitationem et. Quia dolorum quo. Quia nihil aperiam.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 8,
                            Resolution = "Aut quia in aut velit sint ab est iste. Quia et consequuntur accusantium. Quia impedit quae. Nesciunt qui velit maiores nobis consequuntur nostrum. Ipsa impedit assumenda a distinctio.",
                            ResolutionDate = new DateTime(2021, 6, 24, 9, 59, 42, 307, DateTimeKind.Local).AddTicks(6197)
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2020, 6, 1, 22, 4, 42, 122, DateTimeKind.Local).AddTicks(4135),
                            Description = "Adipisci aut et temporibus tempora unde reprehenderit expedita molestiae esse. Fugit ipsa cumque adipisci. Voluptatem cum est eum quos ad et. Non vero sed. Iusto quia atque. Impedit aspernatur fuga a.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 10,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2020, 6, 2, 17, 27, 36, 835, DateTimeKind.Local).AddTicks(6461),
                            Description = "Ratione dolorum impedit molestiae quisquam veritatis nihil incidunt blanditiis quia. Veniam illo esse sint dicta aut vero. Aut veniam eius corporis non. Voluptate earum architecto labore quos et mollitia architecto et nisi. Non distinctio non quibusdam fugit debitis voluptatibus sint.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 18,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2020, 6, 2, 3, 44, 12, 808, DateTimeKind.Local).AddTicks(4971),
                            Description = "Nisi iusto sit saepe soluta omnis. Sit et illo facere occaecati laborum ducimus asperiores et at. Fuga non eligendi molestiae. Corrupti error vero maiores fuga culpa eveniet aperiam et.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 48,
                            Resolution = "Accusamus aut et quo occaecati dolorum non ipsam. Voluptatum ipsam sed aliquid asperiores sapiente corporis sint quia. Quasi quaerat officiis enim. Sunt eveniet voluptate ut iure a doloribus facere. Commodi consequatur vel ea aut.",
                            ResolutionDate = new DateTime(2021, 7, 12, 3, 57, 28, 496, DateTimeKind.Local).AddTicks(1953)
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2020, 6, 1, 21, 25, 51, 747, DateTimeKind.Local).AddTicks(4961),
                            Description = "Aut est a. Omnis libero aspernatur magnam corrupti nobis rem. Et magnam sit quia. Magnam repellat nisi. Quisquam quod non et eum.",
                            IssueStatusId = 4,
                            ProductOSVersionId = 33,
                            Resolution = "Possimus saepe dolores non. Est ut labore incidunt. Repudiandae autem culpa omnis quod recusandae sunt est. Laborum optio sit qui omnis quaerat.",
                            ResolutionDate = new DateTime(2021, 4, 17, 3, 3, 14, 910, DateTimeKind.Local).AddTicks(5682)
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2020, 6, 2, 17, 46, 18, 207, DateTimeKind.Local).AddTicks(5752),
                            Description = "Dolor ab debitis dolores ut. Eum qui voluptates blanditiis corrupti dignissimos ea magnam. Est ducimus repellat et nihil. Iusto autem est.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2020, 6, 2, 18, 47, 7, 997, DateTimeKind.Local).AddTicks(7651),
                            Description = "Labore libero sit magni esse eligendi aut ipsa. Temporibus excepturi est. Sunt necessitatibus consequatur ad laboriosam soluta.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 48,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2020, 6, 1, 19, 47, 20, 990, DateTimeKind.Local).AddTicks(470),
                            Description = "Et quaerat nisi cum voluptatem facere. Libero ut aspernatur tempore repellendus nemo ipsam. Iste nesciunt est sit quia odit sit qui ut corrupti. Odit est ut quibusdam qui aliquam et minus voluptatum nesciunt.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 7,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2020, 6, 1, 22, 2, 53, 520, DateTimeKind.Local).AddTicks(8060),
                            Description = "Nulla nisi voluptas esse. Et sapiente aliquid. Beatae quos et. Nisi quidem cum asperiores.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2020, 6, 2, 3, 58, 52, 122, DateTimeKind.Local).AddTicks(1308),
                            Description = "Unde sint quam perspiciatis in. Eum quia minus possimus ut aut voluptatem tempore aliquam. Eum esse ratione aliquam tempora quisquam explicabo animi sit iure. Deleniti ex labore expedita quisquam quia cupiditate autem vel. Natus molestiae quia cupiditate repudiandae nisi id nobis non vitae. Quam veritatis aut illum dolores minus explicabo eum nihil illum.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 12,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2020, 6, 1, 19, 31, 31, 807, DateTimeKind.Local).AddTicks(7028),
                            Description = "Reiciendis quia voluptatibus. Rem alias dolor qui veritatis. Porro rerum fugit quis iste veritatis quaerat voluptatem sit nemo. Illo possimus temporibus facere eveniet iste magnam non quisquam deleniti.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 10,
                            Resolution = "Dolores aspernatur dolore aut id aut dignissimos itaque dolorem. Accusantium minus enim autem ea sint. Corporis aut veritatis exercitationem et voluptas modi rem molestiae. Reprehenderit dolor aperiam id consequuntur quia veritatis pariatur quidem iusto.",
                            ResolutionDate = new DateTime(2021, 3, 24, 17, 35, 2, 187, DateTimeKind.Local).AddTicks(9170)
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2020, 6, 2, 0, 9, 55, 382, DateTimeKind.Local).AddTicks(9186),
                            Description = "Qui sint facere rem. Excepturi voluptas minima voluptatem at aut rerum quas. Vel velit architecto eaque nesciunt molestiae consequatur adipisci in.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 48,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2020, 6, 2, 6, 38, 34, 209, DateTimeKind.Local).AddTicks(8637),
                            Description = "Cumque soluta sed dolor harum qui numquam autem facere velit. Est cum nobis est repellendus amet repellat ex voluptatibus aut. Quae qui aliquid aut dicta fugiat unde illum.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 23,
                            Resolution = "Nihil enim non enim quia. Est maxime ut eos distinctio voluptate. Deleniti totam ut rerum libero maxime id nisi. Sit et rerum. Et quaerat itaque sit. Fugit officia voluptatibus.",
                            ResolutionDate = new DateTime(2022, 2, 16, 13, 13, 28, 655, DateTimeKind.Local).AddTicks(9676)
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2020, 6, 2, 8, 20, 35, 901, DateTimeKind.Local).AddTicks(9458),
                            Description = "Modi quam possimus consequuntur iusto veritatis nesciunt. Sunt qui aut eos minus. Hic molestias est enim similique alias laudantium dolorem. Optio veritatis nesciunt qui dolore omnis et aut quis. Et id occaecati optio eos dolorem.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 32,
                            Resolution = "Maiores et iste impedit. Fugit perspiciatis necessitatibus sapiente repudiandae provident voluptatem et magnam voluptas. Maiores et accusantium repudiandae doloremque quidem. Eum eum inventore vel dolorem itaque blanditiis. Voluptatem optio dolores repellendus nesciunt. Quis iusto et laudantium dolor dicta libero illum.",
                            ResolutionDate = new DateTime(2021, 7, 1, 20, 5, 28, 894, DateTimeKind.Local).AddTicks(5335)
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2020, 6, 2, 8, 58, 51, 952, DateTimeKind.Local).AddTicks(8923),
                            Description = "Deserunt reprehenderit recusandae fugit et vel molestias ducimus. Distinctio doloremque aspernatur accusamus nostrum quos accusantium impedit esse aut. Laudantium ipsam rerum est omnis accusamus harum beatae perspiciatis.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 17,
                            Resolution = "Voluptate sunt magni quod eum in sit perspiciatis aut qui. Illo est veritatis. Minima laborum voluptates.",
                            ResolutionDate = new DateTime(2022, 1, 8, 2, 55, 8, 874, DateTimeKind.Local).AddTicks(1082)
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2020, 6, 2, 4, 12, 20, 414, DateTimeKind.Local).AddTicks(4579),
                            Description = "Vel dolor velit et. Voluptas excepturi aspernatur eaque et vitae. Dolor assumenda similique aliquam et dolores eum vel magnam minima. Dolore error error dolor et ut repudiandae. Qui aliquam nobis deleniti. Dolorem vitae sit quia suscipit.",
                            IssueStatusId = 1,
                            ProductOSVersionId = 22,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2020, 6, 1, 20, 18, 36, 842, DateTimeKind.Local).AddTicks(2568),
                            Description = "Sunt et molestias nostrum fugit recusandae aut. Non provident cum tenetur veritatis fugiat. Vitae velit consequuntur est est cumque explicabo. Quaerat molestiae dolorem voluptatum dolorum. Rerum alias perspiciatis.",
                            IssueStatusId = 2,
                            ProductOSVersionId = 14,
                            Resolution = ""
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2020, 6, 2, 8, 3, 3, 839, DateTimeKind.Local).AddTicks(9881),
                            Description = "Qui quia iure aspernatur. Laboriosam nisi dolorum iste aut nostrum repellat temporibus porro at. Est architecto deleniti id libero. Molestias voluptas ea quis impedit quam quas natus molestiae.",
                            IssueStatusId = 3,
                            ProductOSVersionId = 49,
                            Resolution = "Laborum et ullam officia autem facere rerum quidem officiis sit. Dolorum aliquam ipsum voluptatem. Sint saepe asperiores in magnam. Nostrum praesentium amet quam quae non dolores enim explicabo.",
                            ResolutionDate = new DateTime(2021, 2, 20, 2, 54, 2, 539, DateTimeKind.Local).AddTicks(5828)
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssueStatusList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OSName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OSName = "Windows"
                        },
                        new
                        {
                            Id = 2,
                            OSName = "Linux"
                        },
                        new
                        {
                            Id = 3,
                            OSName = "MacOS"
                        },
                        new
                        {
                            Id = 4,
                            OSName = "Android"
                        },
                        new
                        {
                            Id = 5,
                            OSName = "iOS"
                        },
                        new
                        {
                            Id = 6,
                            OSName = "Windows Mobile"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Handmade Frozen Sausages"
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Incredible Fresh Ball"
                        },
                        new
                        {
                            Id = 3,
                            ProductName = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 4,
                            ProductName = "Fantastic Cotton Bike"
                        },
                        new
                        {
                            Id = 5,
                            ProductName = "Ergonomic Wooden Tuna"
                        },
                        new
                        {
                            Id = 6,
                            ProductName = "Ergonomic Cotton Chicken"
                        },
                        new
                        {
                            Id = 7,
                            ProductName = "Incredible Fresh Gloves"
                        },
                        new
                        {
                            Id = 8,
                            ProductName = "Awesome Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            ProductName = "Refined Granite Bike"
                        },
                        new
                        {
                            Id = 10,
                            ProductName = "Refined Steel Towels"
                        },
                        new
                        {
                            Id = 11,
                            ProductName = "Small Frozen Chicken"
                        },
                        new
                        {
                            Id = 12,
                            ProductName = "Ergonomic Granite Computer"
                        },
                        new
                        {
                            Id = 13,
                            ProductName = "Ergonomic Concrete Soap"
                        },
                        new
                        {
                            Id = 14,
                            ProductName = "Incredible Granite Mouse"
                        },
                        new
                        {
                            Id = 15,
                            ProductName = "Awesome Plastic Computer"
                        },
                        new
                        {
                            Id = 16,
                            ProductName = "Awesome Rubber Bike"
                        },
                        new
                        {
                            Id = 17,
                            ProductName = "Refined Soft Chips"
                        },
                        new
                        {
                            Id = 18,
                            ProductName = "Unbranded Soft Shirt"
                        },
                        new
                        {
                            Id = 19,
                            ProductName = "Fantastic Concrete Soap"
                        },
                        new
                        {
                            Id = 20,
                            ProductName = "Intelligent Granite Gloves"
                        },
                        new
                        {
                            Id = 21,
                            ProductName = "Small Plastic Pants"
                        },
                        new
                        {
                            Id = 22,
                            ProductName = "Ergonomic Plastic Shoes"
                        },
                        new
                        {
                            Id = 23,
                            ProductName = "Sleek Frozen Soap"
                        },
                        new
                        {
                            Id = 24,
                            ProductName = "Sleek Frozen Mouse"
                        },
                        new
                        {
                            Id = 25,
                            ProductName = "Ergonomic Steel Shirt"
                        },
                        new
                        {
                            Id = 26,
                            ProductName = "Rustic Frozen Car"
                        },
                        new
                        {
                            Id = 27,
                            ProductName = "Handcrafted Plastic Sausages"
                        },
                        new
                        {
                            Id = 28,
                            ProductName = "Tasty Frozen Ball"
                        },
                        new
                        {
                            Id = 29,
                            ProductName = "Awesome Wooden Keyboard"
                        },
                        new
                        {
                            Id = 30,
                            ProductName = "Incredible Metal Gloves"
                        },
                        new
                        {
                            Id = 31,
                            ProductName = "Awesome Frozen Chicken"
                        },
                        new
                        {
                            Id = 32,
                            ProductName = "Gorgeous Concrete Keyboard"
                        },
                        new
                        {
                            Id = 33,
                            ProductName = "Licensed Granite Chips"
                        },
                        new
                        {
                            Id = 34,
                            ProductName = "Generic Steel Soap"
                        },
                        new
                        {
                            Id = 35,
                            ProductName = "Generic Plastic Bacon"
                        },
                        new
                        {
                            Id = 36,
                            ProductName = "Licensed Fresh Cheese"
                        },
                        new
                        {
                            Id = 37,
                            ProductName = "Tasty Concrete Bike"
                        },
                        new
                        {
                            Id = 38,
                            ProductName = "Awesome Granite Mouse"
                        },
                        new
                        {
                            Id = 39,
                            ProductName = "Fantastic Steel Pants"
                        },
                        new
                        {
                            Id = 40,
                            ProductName = "Ergonomic Granite Mouse"
                        },
                        new
                        {
                            Id = 41,
                            ProductName = "Incredible Concrete Ball"
                        },
                        new
                        {
                            Id = 42,
                            ProductName = "Incredible Frozen Car"
                        },
                        new
                        {
                            Id = 43,
                            ProductName = "Sleek Fresh Fish"
                        },
                        new
                        {
                            Id = 44,
                            ProductName = "Gorgeous Plastic Shoes"
                        },
                        new
                        {
                            Id = 45,
                            ProductName = "Ergonomic Steel Ball"
                        },
                        new
                        {
                            Id = 46,
                            ProductName = "Incredible Plastic Soap"
                        },
                        new
                        {
                            Id = 47,
                            ProductName = "Practical Soft Gloves"
                        },
                        new
                        {
                            Id = 48,
                            ProductName = "Fantastic Plastic Hat"
                        },
                        new
                        {
                            Id = 49,
                            ProductName = "Ergonomic Frozen Shirt"
                        },
                        new
                        {
                            Id = 50,
                            ProductName = "Sleek Fresh Mouse"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatingSystemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProductId", "OperatingSystemId", "VersionId");

                    b.HasIndex("OperatingSystemId");

                    b.HasIndex("VersionId");

                    b.ToTable("ProductOSVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperatingSystemId = 2,
                            ProductId = 6,
                            VersionId = 45
                        },
                        new
                        {
                            Id = 2,
                            OperatingSystemId = 5,
                            ProductId = 50,
                            VersionId = 41
                        },
                        new
                        {
                            Id = 3,
                            OperatingSystemId = 2,
                            ProductId = 39,
                            VersionId = 32
                        },
                        new
                        {
                            Id = 4,
                            OperatingSystemId = 6,
                            ProductId = 35,
                            VersionId = 28
                        },
                        new
                        {
                            Id = 5,
                            OperatingSystemId = 5,
                            ProductId = 35,
                            VersionId = 46
                        },
                        new
                        {
                            Id = 6,
                            OperatingSystemId = 1,
                            ProductId = 20,
                            VersionId = 29
                        },
                        new
                        {
                            Id = 7,
                            OperatingSystemId = 2,
                            ProductId = 48,
                            VersionId = 10
                        },
                        new
                        {
                            Id = 8,
                            OperatingSystemId = 1,
                            ProductId = 9,
                            VersionId = 2
                        },
                        new
                        {
                            Id = 9,
                            OperatingSystemId = 4,
                            ProductId = 14,
                            VersionId = 12
                        },
                        new
                        {
                            Id = 10,
                            OperatingSystemId = 6,
                            ProductId = 1,
                            VersionId = 9
                        },
                        new
                        {
                            Id = 11,
                            OperatingSystemId = 6,
                            ProductId = 9,
                            VersionId = 39
                        },
                        new
                        {
                            Id = 12,
                            OperatingSystemId = 6,
                            ProductId = 42,
                            VersionId = 35
                        },
                        new
                        {
                            Id = 13,
                            OperatingSystemId = 2,
                            ProductId = 5,
                            VersionId = 31
                        },
                        new
                        {
                            Id = 14,
                            OperatingSystemId = 1,
                            ProductId = 8,
                            VersionId = 25
                        },
                        new
                        {
                            Id = 15,
                            OperatingSystemId = 2,
                            ProductId = 35,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 16,
                            OperatingSystemId = 4,
                            ProductId = 25,
                            VersionId = 46
                        },
                        new
                        {
                            Id = 17,
                            OperatingSystemId = 3,
                            ProductId = 11,
                            VersionId = 16
                        },
                        new
                        {
                            Id = 18,
                            OperatingSystemId = 4,
                            ProductId = 41,
                            VersionId = 48
                        },
                        new
                        {
                            Id = 19,
                            OperatingSystemId = 6,
                            ProductId = 43,
                            VersionId = 13
                        },
                        new
                        {
                            Id = 20,
                            OperatingSystemId = 5,
                            ProductId = 44,
                            VersionId = 13
                        },
                        new
                        {
                            Id = 21,
                            OperatingSystemId = 5,
                            ProductId = 30,
                            VersionId = 14
                        },
                        new
                        {
                            Id = 22,
                            OperatingSystemId = 4,
                            ProductId = 23,
                            VersionId = 49
                        },
                        new
                        {
                            Id = 23,
                            OperatingSystemId = 6,
                            ProductId = 40,
                            VersionId = 46
                        },
                        new
                        {
                            Id = 24,
                            OperatingSystemId = 2,
                            ProductId = 11,
                            VersionId = 37
                        },
                        new
                        {
                            Id = 25,
                            OperatingSystemId = 5,
                            ProductId = 49,
                            VersionId = 16
                        },
                        new
                        {
                            Id = 26,
                            OperatingSystemId = 3,
                            ProductId = 35,
                            VersionId = 42
                        },
                        new
                        {
                            Id = 27,
                            OperatingSystemId = 5,
                            ProductId = 47,
                            VersionId = 47
                        },
                        new
                        {
                            Id = 28,
                            OperatingSystemId = 5,
                            ProductId = 16,
                            VersionId = 27
                        },
                        new
                        {
                            Id = 29,
                            OperatingSystemId = 3,
                            ProductId = 44,
                            VersionId = 18
                        },
                        new
                        {
                            Id = 30,
                            OperatingSystemId = 6,
                            ProductId = 41,
                            VersionId = 50
                        },
                        new
                        {
                            Id = 31,
                            OperatingSystemId = 2,
                            ProductId = 22,
                            VersionId = 31
                        },
                        new
                        {
                            Id = 32,
                            OperatingSystemId = 4,
                            ProductId = 18,
                            VersionId = 13
                        },
                        new
                        {
                            Id = 33,
                            OperatingSystemId = 2,
                            ProductId = 12,
                            VersionId = 35
                        },
                        new
                        {
                            Id = 34,
                            OperatingSystemId = 5,
                            ProductId = 8,
                            VersionId = 38
                        },
                        new
                        {
                            Id = 35,
                            OperatingSystemId = 6,
                            ProductId = 1,
                            VersionId = 6
                        },
                        new
                        {
                            Id = 36,
                            OperatingSystemId = 6,
                            ProductId = 29,
                            VersionId = 39
                        },
                        new
                        {
                            Id = 37,
                            OperatingSystemId = 1,
                            ProductId = 33,
                            VersionId = 24
                        },
                        new
                        {
                            Id = 38,
                            OperatingSystemId = 6,
                            ProductId = 22,
                            VersionId = 47
                        },
                        new
                        {
                            Id = 39,
                            OperatingSystemId = 2,
                            ProductId = 16,
                            VersionId = 48
                        },
                        new
                        {
                            Id = 40,
                            OperatingSystemId = 4,
                            ProductId = 38,
                            VersionId = 7
                        },
                        new
                        {
                            Id = 41,
                            OperatingSystemId = 6,
                            ProductId = 32,
                            VersionId = 45
                        },
                        new
                        {
                            Id = 42,
                            OperatingSystemId = 5,
                            ProductId = 46,
                            VersionId = 4
                        },
                        new
                        {
                            Id = 43,
                            OperatingSystemId = 4,
                            ProductId = 6,
                            VersionId = 12
                        },
                        new
                        {
                            Id = 44,
                            OperatingSystemId = 3,
                            ProductId = 3,
                            VersionId = 12
                        },
                        new
                        {
                            Id = 45,
                            OperatingSystemId = 5,
                            ProductId = 7,
                            VersionId = 5
                        },
                        new
                        {
                            Id = 46,
                            OperatingSystemId = 2,
                            ProductId = 10,
                            VersionId = 41
                        },
                        new
                        {
                            Id = 47,
                            OperatingSystemId = 2,
                            ProductId = 21,
                            VersionId = 28
                        },
                        new
                        {
                            Id = 48,
                            OperatingSystemId = 2,
                            ProductId = 29,
                            VersionId = 42
                        },
                        new
                        {
                            Id = 49,
                            OperatingSystemId = 1,
                            ProductId = 27,
                            VersionId = 15
                        },
                        new
                        {
                            Id = 50,
                            OperatingSystemId = 1,
                            ProductId = 35,
                            VersionId = 16
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VersionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VersionName = "7.7.0.8"
                        },
                        new
                        {
                            Id = 2,
                            VersionName = "3.8.3.3"
                        },
                        new
                        {
                            Id = 3,
                            VersionName = "3.7.3.0"
                        },
                        new
                        {
                            Id = 4,
                            VersionName = "0.7.8.7"
                        },
                        new
                        {
                            Id = 5,
                            VersionName = "4.5.9.0"
                        },
                        new
                        {
                            Id = 6,
                            VersionName = "7.7.6.7"
                        },
                        new
                        {
                            Id = 7,
                            VersionName = "8.9.8.7"
                        },
                        new
                        {
                            Id = 8,
                            VersionName = "2.9.6.9"
                        },
                        new
                        {
                            Id = 9,
                            VersionName = "9.5.4.6"
                        },
                        new
                        {
                            Id = 10,
                            VersionName = "4.2.6.4"
                        },
                        new
                        {
                            Id = 11,
                            VersionName = "9.0.2.6"
                        },
                        new
                        {
                            Id = 12,
                            VersionName = "4.2.3.6"
                        },
                        new
                        {
                            Id = 13,
                            VersionName = "6.2.5.8"
                        },
                        new
                        {
                            Id = 14,
                            VersionName = "5.7.4.0"
                        },
                        new
                        {
                            Id = 15,
                            VersionName = "0.2.9.4"
                        },
                        new
                        {
                            Id = 16,
                            VersionName = "9.6.0.3"
                        },
                        new
                        {
                            Id = 17,
                            VersionName = "1.3.0.4"
                        },
                        new
                        {
                            Id = 18,
                            VersionName = "2.2.3.2"
                        },
                        new
                        {
                            Id = 19,
                            VersionName = "8.5.1.6"
                        },
                        new
                        {
                            Id = 20,
                            VersionName = "5.0.2.5"
                        },
                        new
                        {
                            Id = 21,
                            VersionName = "5.2.0.9"
                        },
                        new
                        {
                            Id = 22,
                            VersionName = "4.7.4.1"
                        },
                        new
                        {
                            Id = 23,
                            VersionName = "1.4.5.1"
                        },
                        new
                        {
                            Id = 24,
                            VersionName = "3.2.4.3"
                        },
                        new
                        {
                            Id = 25,
                            VersionName = "9.8.5.1"
                        },
                        new
                        {
                            Id = 26,
                            VersionName = "2.9.3.4"
                        },
                        new
                        {
                            Id = 27,
                            VersionName = "9.2.0.0"
                        },
                        new
                        {
                            Id = 28,
                            VersionName = "6.7.5.0"
                        },
                        new
                        {
                            Id = 29,
                            VersionName = "0.3.9.7"
                        },
                        new
                        {
                            Id = 30,
                            VersionName = "5.0.9.3"
                        },
                        new
                        {
                            Id = 31,
                            VersionName = "9.9.3.7"
                        },
                        new
                        {
                            Id = 32,
                            VersionName = "6.1.9.6"
                        },
                        new
                        {
                            Id = 33,
                            VersionName = "0.7.6.6"
                        },
                        new
                        {
                            Id = 34,
                            VersionName = "5.1.3.6"
                        },
                        new
                        {
                            Id = 35,
                            VersionName = "8.5.9.1"
                        },
                        new
                        {
                            Id = 36,
                            VersionName = "7.3.4.3"
                        },
                        new
                        {
                            Id = 37,
                            VersionName = "9.5.1.9"
                        },
                        new
                        {
                            Id = 38,
                            VersionName = "3.6.7.9"
                        },
                        new
                        {
                            Id = 39,
                            VersionName = "9.1.2.3"
                        },
                        new
                        {
                            Id = 40,
                            VersionName = "5.5.8.8"
                        },
                        new
                        {
                            Id = 41,
                            VersionName = "3.3.9.9"
                        },
                        new
                        {
                            Id = 42,
                            VersionName = "0.8.4.8"
                        },
                        new
                        {
                            Id = 43,
                            VersionName = "0.3.8.9"
                        },
                        new
                        {
                            Id = 44,
                            VersionName = "1.7.5.5"
                        },
                        new
                        {
                            Id = 45,
                            VersionName = "4.0.8.0"
                        },
                        new
                        {
                            Id = 46,
                            VersionName = "9.9.3.4"
                        },
                        new
                        {
                            Id = 47,
                            VersionName = "9.7.7.3"
                        },
                        new
                        {
                            Id = 48,
                            VersionName = "8.9.0.3"
                        },
                        new
                        {
                            Id = 49,
                            VersionName = "7.1.8.3"
                        },
                        new
                        {
                            Id = 50,
                            VersionName = "3.5.2.0"
                        });
                });

            modelBuilder.Entity("BugTracker.Data.Models.Issue", b =>
                {
                    b.HasOne("BugTracker.Data.Models.IssueStatus", "IssueStatus")
                        .WithMany()
                        .HasForeignKey("IssueStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.ProductOSVersion", "ProductOSVersion")
                        .WithMany()
                        .HasForeignKey("ProductOSVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BugTracker.Data.Models.ProductOSVersion", b =>
                {
                    b.HasOne("BugTracker.Data.Models.OperatingSystem", "OperatingSystem")
                        .WithMany()
                        .HasForeignKey("OperatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTracker.Data.Models.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
